In [137]:
import random
import time

import tensorflow as tf
from tensorflow.keras import Sequential

from tensorflow.keras.layers import (
    Input,
    Conv1D,
    BatchNormalization,
    Activation,
    MaxPooling1D,
    Flatten,
    Dense,
    Dropout,
)
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam

from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report, confusion_matrix,  precision_score, recall_score, f1_score, accuracy_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler, Normalizer, OrdinalEncoder, MinMaxScaler,  LabelEncoder
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.feature_selection import SelectKBest, chi2, SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline

import numpy as np
import pandas as pd

In [138]:
column_names = [
    "duration",
    "protocol_type",
    "service",
    "flag",
    "src_bytes",
    "dst_bytes",
    "land",
    "wrong_fragment",
    "urgent",
    "hot",
    "num_failed_logins",
    "logged_in",
    "num_compromised",
    "root_shell",
    "su_attempted",
    "num_root",
    "num_file_creations",
    "num_shells",
    "num_access_files",
    "num_outbound_cmds",
    "is_host_login",
    "is_guest_login",
    "count",
    "srv_count",
    "serror_rate",
    "srv_serror_rate",
    "rerror_rate",
    "srv_rerror_rate",
    "same_srv_rate",
    "diff_srv_rate",
    "srv_diff_host_rate",
    "dst_host_count",
    "dst_host_srv_count",
    "dst_host_same_srv_rate",
    "dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate",
    "dst_host_serror_rate",
    "dst_host_srv_serror_rate",
    "dst_host_rerror_rate",
    "dst_host_srv_rerror_rate",
    "label",
    "difficulty",
]



train_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DATASETS/NSLKDD/NSL_KDD_Train.csv",names=column_names, header=None)
test_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DATASETS/NSLKDD/NSL_KDD_Test.csv",names=column_names, header=None)

In [139]:
test_df.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'label', 'difficulty'],
      dtype='object')

In [140]:
test_df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,difficulty
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.04,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,NaN
1,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,NaN
2,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.04,0.61,0.02,0.0,0.0,0.00,0.00,normal,NaN
3,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.00,1.00,0.28,0.0,0.0,0.00,0.00,saint,NaN
4,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.31,0.17,0.03,0.02,0.0,0.0,0.83,0.71,mscan,NaN

In [141]:
print("Training data shape:", train_df.shape)
print("Testing data shape:", test_df.shape)
print(train_df.head())

Training data shape: (125973, 43)
Testing data shape: (22544, 43)
   duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0         0           tcp  ftp_data   SF        491          0     0
1         0           udp     other   SF        146          0     0
2         0           tcp   private   S0          0          0     0
3         0           tcp      http   SF        232       8153     0
4         0           tcp      http   SF        199        420     0

   wrong_fragment  urgent  hot  ...  dst_host_same_srv_rate  \
0               0       0    0  ...                    0.17
1               0       0    0  ...                    0.00
2               0       0    0  ...                    0.10
3               0       0    0  ...                    1.00
4               0       0    0  ...                    1.00

   dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                    0.03                         0.17
1                    0.60                         0.88
2                    0.05                         0.00
3                    0.00                         0.03
4                    0.00                         0.00

   dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                         0.00                  0.00
1                         0.00                  0.00
2                         0.00                  1.00
3                         0.04                  0.03
4                         0.00                  0.00

   dst_host_srv_serror_rate  dst_host_rerror_rate  dst_host_srv_rerror_rate  \
0                      0.00                  0.05                      0.00
1                      0.00                  0.00                      0.00
2                      1.00                  0.00                      0.00
3                      0.01                  0.00                      0.01
4                      0.00                  0.00                      0.00

     label  difficulty
0   normal         NaN
1   normal         NaN
2  neptune         NaN
3   normal         NaN
4   normal         NaN

[5 rows x 43 columns]

In [142]:
test_df.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'label', 'difficulty'],
      dtype='object')

In [88]:
test_df['label'].value_counts()

label
normal             9711
neptune            4657
guess_passwd       1231
mscan               996
warezmaster         944
apache2             737
satan               735
processtable        685
smurf               665
back                359
snmpguess           331
saint               319
mailbomb            293
snmpgetattack       178
portsweep           157
ipsweep             141
httptunnel          133
nmap                 73
pod                  41
buffer_overflow      20
multihop             18
named                17
ps                   15
sendmail             14
xterm                13
rootkit              13
teardrop             12
xlock                 9
land                  7
xsnoop                4
ftp_write             3
loadmodule            2
worm                  2
perl                  2
sqlattack             2
udpstorm              2
phf                   2
imap                  1
Name: count, dtype: int64

In [143]:
all_df = pd.concat([train_df, test_df], axis=0)

In [148]:
train_labels = (
    all_df["label"]
    .astype(str)
    .str.strip()
    .str.rstrip(".")
)

test_labels = (
    test_df["label"]
    .astype(str)
    .str.strip()
    .str.rstrip(".")
)

y_train_all = (train_labels != "normal").astype(np.int32).to_numpy()
y_test = (test_labels != "normal").astype(np.int32).to_numpy()

print("Training label values:", np.unique(y_train_all))
print("Testing label values:", np.unique(y_test))

Training label values: [0 1]
Testing label values: [0 1]

In [149]:
X_train_all_df = all_df.drop(
    columns=["label", "difficulty"]
).copy()

X_test_df = test_df.drop(
    columns=["label", "difficulty"]
).copy()

print("Training features:", X_train_all_df.shape)
print("Testing features: ", X_test_df.shape)

Training features: (148517, 41)
Testing features:  (22544, 41)

# **An Empirical Study on Network Anomaly Detection using Convolutional Neural Networks [33]**

In [ ]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

In [ ]:
categorical_columns = [
    "protocol_type",
    "service",
    "flag",
]

numerical_columns = [
    column
    for column in X_train_df.columns
    if column not in categorical_columns
]

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            StandardScaler(),
            numerical_columns,
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False,
            ),
            categorical_columns,
        ),
    ]
)

In [ ]:
X_train = preprocessor.fit_transform(X_train_df)
X_test = preprocessor.transform(X_test_df)

X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)

print("Processed training shape:", X_train.shape)
print("Processed testing shape:", X_test.shape)

Processed training shape: (125973, 122)
Processed testing shape: (22544, 122)

In [ ]:
X_train = np.expand_dims(X_train, axis=-1)
X_test = np.expand_dims(X_test, axis=-1)

print("CNN training shape:", X_train.shape)
print("CNN testing shape:", X_test.shape)

CNN training shape: (125973, 122, 1)
CNN testing shape: (22544, 122, 1)

In [ ]:
y_train_encoded = to_categorical(y_train, num_classes=2)
y_test_encoded = to_categorical(y_test, num_classes=2)

print(y_train_encoded.shape)
print(y_train_encoded[:5])

(125973, 2)
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]

In [ ]:
model = Sequential([
    Input(shape=(122, 1)),

    Conv1D(
        filters=64,
        kernel_size=3,
        strides=1,
        padding="same",
        use_bias=False,
    ),
    Activation("relu"),
    BatchNormalization(),
    Dropout(rate=0.5),

    MaxPooling1D(
        pool_size=2,
        strides=2,
        padding="valid",
    ),

    Flatten(),

    Dense(
        units=64,
        use_bias=False,
    ),
    Activation("relu"),
    BatchNormalization(),
    Dropout(rate=0.5),

    Dense(
        units=2,
        activation="softmax",
    ),
])

In [ ]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"],
)
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 122, 64)        │           192 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 122, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 122, 64)        │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 122, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 61, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 3904)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │       249,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_1 (Activation)       │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 2)              │           130 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 250,690 (979.26 KB)

 Trainable params: 250,434 (978.26 KB)

 Non-trainable params: 256 (1.00 KB)

In [ ]:
y_train_encoded = to_categorical(y_train, num_classes=2)
y_test_encoded = to_categorical(y_test, num_classes=2)

In [ ]:
history = model.fit(
    X_train,
    y_train_encoded,
    epochs=10,
    batch_size=32,
    shuffle=True,
    verbose=2,
)

Epoch 1/10
3937/3937 - 17s - 4ms/step - accuracy: 0.9761 - loss: 0.0696
Epoch 2/10
3937/3937 - 7s - 2ms/step - accuracy: 0.9819 - loss: 0.0510
Epoch 3/10
3937/3937 - 7s - 2ms/step - accuracy: 0.9838 - loss: 0.0457
Epoch 4/10
3937/3937 - 7s - 2ms/step - accuracy: 0.9849 - loss: 0.0433
Epoch 5/10
3937/3937 - 7s - 2ms/step - accuracy: 0.9849 - loss: 0.0428
Epoch 6/10
3937/3937 - 7s - 2ms/step - accuracy: 0.9860 - loss: 0.0404
Epoch 7/10
3937/3937 - 7s - 2ms/step - accuracy: 0.9864 - loss: 0.0399
Epoch 8/10
3937/3937 - 7s - 2ms/step - accuracy: 0.9856 - loss: 0.0407
Epoch 9/10
3937/3937 - 7s - 2ms/step - accuracy: 0.9868 - loss: 0.0386
Epoch 10/10
3937/3937 - 7s - 2ms/step - accuracy: 0.9867 - loss: 0.0375

In [ ]:
test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test_encoded,
    batch_size=32,
    verbose=0,
)

print("\nTest results")
print("------------")
print(f"Loss:     {test_loss:.6f}")
print(f"Accuracy: {test_accuracy:.6f}")
print(f"Accuracy: {test_accuracy * 100:.2f}%")

Test results
------------
Loss:     1.431539
Accuracy: 0.760158
Accuracy: 76.02%

In [ ]:

predicted_probabilities = model.predict(
    X_test,
    batch_size=32,
    verbose=0,
)

y_pred = np.argmax(
    predicted_probabilities,
    axis=1,
)


cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = cm.ravel()


print("\nClassification report")
print("---------------------")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=["normal", "attack"],
        digits=4,
        zero_division=0,
    )
)

attack_precision = precision_score(
    y_test,
    y_pred,
    pos_label=1,
    average="binary",
    zero_division=0,
)

attack_detection_rate = recall_score(
    y_test,
    y_pred,
    pos_label=1,
    average="binary",
    zero_division=0,
)

false_positive_rate = (
    fp / (fp + tn)
    if (fp + tn) > 0
    else 0.0
)

attack_f1_score = f1_score(
    y_test,
    y_pred,
    pos_label=1,
    average="binary",
    zero_division=0,
)




print("Confusion matrix")
print("----------------")
print(cm)

print("\nAttack-class metrics")
print("--------------------")
print(f"Detection rate : {attack_detection_rate:.4f} "
      f"({attack_detection_rate * 100:.2f}%)")
print(f"Precision      : {attack_precision:.4f} "
      f"({attack_precision * 100:.2f}%)")
print(f"FPR            : {false_positive_rate:.4f} "
      f"({false_positive_rate * 100:.2f}%)")
print(f"F1 score       : {attack_f1_score:.4f} "
      f"({attack_f1_score * 100:.2f}%)")

Classification report
---------------------
              precision    recall  f1-score   support

      normal     0.6512    0.9546    0.7742      9711
      attack     0.9469    0.6130    0.7442     12833

    accuracy                         0.7602     22544
   macro avg     0.7990    0.7838    0.7592     22544
weighted avg     0.8195    0.7602    0.7572     22544

Confusion matrix
----------------
[[9270  441]
 [4966 7867]]

Attack-class metrics
--------------------
Detection rate : 0.6130 (61.30%)
Precision      : 0.9469 (94.69%)
FPR            : 0.0454 (4.54%)
F1 score       : 0.7442 (74.42%)

In [ ]:
model.save("/content/drive/MyDrive/1DCNN_Kwon.keras")

# **Deep Learning Approach for Intelligent Intrusion Detection System [69]**

In [150]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

In [152]:
X_train_df, X_val_df, y_train, y_val = train_test_split(
    X_train_all_df,
    y_train_all,
    test_size=0.05,
    random_state=SEED,
    stratify=y_train_all,
)

print("\nData split")
print("----------")
print("Training:   ", X_train_df.shape)
print("Validation: ", X_val_df.shape)
print("Testing:    ", X_test_df.shape)

Data split
----------
Training:    (141091, 41)
Validation:  (7426, 41)
Testing:     (22544, 41)

In [153]:
categorical_columns = [
    "protocol_type",
    "service",
    "flag",
]

encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value",
    unknown_value=-1,
)

X_train_df.loc[:, categorical_columns] = encoder.fit_transform(
    X_train_df[categorical_columns]
)

X_val_df.loc[:, categorical_columns] = encoder.transform(
    X_val_df[categorical_columns]
)

X_test_df.loc[:, categorical_columns] = encoder.transform(
    X_test_df[categorical_columns]
)



X_train = X_train_df.astype(np.float32).to_numpy()
X_val = X_val_df.astype(np.float32).to_numpy()
X_test = X_test_df.astype(np.float32).to_numpy()

In [154]:
normalizer = Normalizer(norm="l2")

X_train = normalizer.fit_transform(X_train).astype(np.float32)
X_val = normalizer.transform(X_val).astype(np.float32)
X_test = normalizer.transform(X_test).astype(np.float32)

print("\nProcessed shapes")
print("----------------")
print("Training:   ", X_train.shape)
print("Validation: ", X_val.shape)
print("Testing:    ", X_test.shape)

Processed shapes
----------------
Training:    (141091, 41)
Validation:  (7426, 41)
Testing:     (22544, 41)

In [155]:
model = tf.keras.Sequential(
    [
        tf.keras.layers.Input(
            shape=(41,),
            name="nsl_kdd_input",
        ),

        tf.keras.layers.Dense(
            units=1024,
            activation="relu",
            name="dense_1024",
        ),
        tf.keras.layers.BatchNormalization(
            name="batch_norm_1024",
        ),
        tf.keras.layers.Dropout(
            rate=0.01,
            name="dropout_1024",
        ),

        tf.keras.layers.Dense(
            units=768,
            activation="relu",
            name="dense_768",
        ),
        tf.keras.layers.BatchNormalization(
            name="batch_norm_768",
        ),
        tf.keras.layers.Dropout(
            rate=0.01,
            name="dropout_768",
        ),

        tf.keras.layers.Dense(
            units=512,
            activation="relu",
            name="dense_512",
        ),
        tf.keras.layers.BatchNormalization(
            name="batch_norm_512",
        ),
        tf.keras.layers.Dropout(
            rate=0.01,
            name="dropout_512",
        ),

        tf.keras.layers.Dense(
            units=256,
            activation="relu",
            name="dense_256",
        ),
        tf.keras.layers.BatchNormalization(
            name="batch_norm_256",
        ),
        tf.keras.layers.Dropout(
            rate=0.01,
            name="dropout_256",
        ),

        tf.keras.layers.Dense(
            units=128,
            activation="relu",
            name="dense_128",
        ),
        tf.keras.layers.BatchNormalization(
            name="batch_norm_128",
        ),
        tf.keras.layers.Dropout(
            rate=0.01,
            name="dropout_128",
        ),
        tf.keras.layers.Dense(
            units=1,
            activation="sigmoid",
            name="binary_output",
        ),
    ],
    name="nsl_kdd_binary_dnn",
)

In [156]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.1,
    ),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=[
        tf.keras.metrics.BinaryAccuracy(
            name="accuracy",
            threshold=0.5,
        ),
        tf.keras.metrics.Precision(
            name="precision",
            thresholds=0.5,
        ),
        tf.keras.metrics.Recall(
            name="recall",
            thresholds=0.5,
        ),
        tf.keras.metrics.AUC(
            name="auc",
        ),
    ],
)

model.summary()

Model: "nsl_kdd_binary_dnn"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1024 (Dense)              │ (None, 1024)           │        43,008 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_norm_1024                 │ (None, 1024)           │         4,096 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1024 (Dropout)          │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_768 (Dense)               │ (None, 768)            │       787,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_norm_768                  │ (None, 768)            │         3,072 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_768 (Dropout)           │ (None, 768)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_512 (Dense)               │ (None, 512)            │       393,728 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_norm_512                  │ (None, 512)            │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_512 (Dropout)           │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_256 (Dense)               │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_norm_256                  │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_256 (Dropout)           │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_128 (Dense)               │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_norm_128                  │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_128 (Dropout)           │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ binary_output (Dense)           │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,399,041 (5.34 MB)

 Trainable params: 1,393,665 (5.32 MB)

 Non-trainable params: 5,376 (21.00 KB)

In [157]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=200,
    batch_size=64,
    shuffle=True,
    verbose=2,
)

Epoch 1/200
2205/2205 - 36s - 16ms/step - accuracy: 0.9240 - auc: 0.9802 - loss: 0.1806 - precision: 0.9307 - recall: 0.9097 - val_accuracy: 0.9271 - val_auc: 0.9881 - val_loss: 0.1398 - val_precision: 0.9100 - val_recall: 0.9418
Epoch 2/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9358 - auc: 0.9844 - loss: 0.1582 - precision: 0.9426 - recall: 0.9229 - val_accuracy: 0.9175 - val_auc: 0.9866 - val_loss: 12592.6396 - val_precision: 0.8615 - val_recall: 0.9871
Epoch 3/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9484 - auc: 0.9892 - loss: 0.1291 - precision: 0.9523 - recall: 0.9398 - val_accuracy: 0.9414 - val_auc: 0.9807 - val_loss: 11961312.0000 - val_precision: 0.9280 - val_recall: 0.9521
Epoch 4/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9533 - auc: 0.9906 - loss: 0.1193 - precision: 0.9579 - recall: 0.9444 - val_accuracy: 0.9379 - val_auc: 0.9763 - val_loss: 4876812800.0000 - val_precision: 0.9924 - val_recall: 0.8777
Epoch 5/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9583 - auc: 0.9918 - loss: 0.1101 - precision: 0.9623 - recall: 0.9506 - val_accuracy: 0.9533 - val_auc: 0.9901 - val_loss: 27977799680.0000 - val_precision: 0.9369 - val_recall: 0.9681
Epoch 6/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9612 - auc: 0.9928 - loss: 0.1027 - precision: 0.9652 - recall: 0.9537 - val_accuracy: 0.9620 - val_auc: 0.9905 - val_loss: 8533861376.0000 - val_precision: 0.9600 - val_recall: 0.9611
Epoch 7/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9627 - auc: 0.9925 - loss: 0.1026 - precision: 0.9660 - recall: 0.9561 - val_accuracy: 0.9690 - val_auc: 0.9945 - val_loss: 26032.8301 - val_precision: 0.9780 - val_recall: 0.9572
Epoch 8/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9661 - auc: 0.9932 - loss: 0.0967 - precision: 0.9694 - recall: 0.9598 - val_accuracy: 0.9666 - val_auc: 0.9933 - val_loss: 20758088.0000 - val_precision: 0.9790 - val_recall: 0.9510
Epoch 9/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9667 - auc: 0.9936 - loss: 0.0941 - precision: 0.9710 - recall: 0.9594 - val_accuracy: 0.9609 - val_auc: 0.9930 - val_loss: 6182263808.0000 - val_precision: 0.9489 - val_recall: 0.9712
Epoch 10/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9659 - auc: 0.9931 - loss: 0.0982 - precision: 0.9700 - recall: 0.9587 - val_accuracy: 0.9717 - val_auc: 0.9952 - val_loss: 0.0929 - val_precision: 0.9895 - val_recall: 0.9513
Epoch 11/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9679 - auc: 0.9940 - loss: 0.0902 - precision: 0.9737 - recall: 0.9593 - val_accuracy: 0.9293 - val_auc: 0.9907 - val_loss: 0.1921 - val_precision: 0.8776 - val_recall: 0.9913
Epoch 12/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9667 - auc: 0.9931 - loss: 0.0976 - precision: 0.9710 - recall: 0.9594 - val_accuracy: 0.9719 - val_auc: 0.9950 - val_loss: 150596.9062 - val_precision: 0.9907 - val_recall: 0.9505
Epoch 13/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9722 - auc: 0.9946 - loss: 0.0825 - precision: 0.9758 - recall: 0.9661 - val_accuracy: 0.9592 - val_auc: 0.9958 - val_loss: 144709.1250 - val_precision: 0.9940 - val_recall: 0.9208
Epoch 14/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9731 - auc: 0.9949 - loss: 0.0804 - precision: 0.9764 - recall: 0.9674 - val_accuracy: 0.9663 - val_auc: 0.9955 - val_loss: 4018.3037 - val_precision: 0.9952 - val_recall: 0.9345
Epoch 15/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9712 - auc: 0.9939 - loss: 0.0897 - precision: 0.9744 - recall: 0.9655 - val_accuracy: 0.9740 - val_auc: 0.9958 - val_loss: 22534076416.0000 - val_precision: 0.9788 - val_recall: 0.9670
Epoch 16/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9749 - auc: 0.9952 - loss: 0.0764 - precision: 0.9790 - recall: 0.9687 - val_accuracy: 0.9589 - val_auc: 0.9965 - val_loss: 0.0909 - val_precision: 0.9291 - val_recall: 0.9902
Epoch 17/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9733 - auc: 0.9947 - loss: 0.0816 - precision: 0.9775 - recall: 0.9668 - val_accuracy: 0.9758 - val_auc: 0.9946 - val_loss: 107390368.0000 - val_precision: 0.9696 - val_recall: 0.9804
Epoch 18/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9760 - auc: 0.9957 - loss: 0.0715 - precision: 0.9802 - recall: 0.9697 - val_accuracy: 0.9803 - val_auc: 0.9964 - val_loss: 696839.3750 - val_precision: 0.9867 - val_recall: 0.9723
Epoch 19/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9682 - auc: 0.9928 - loss: 0.0980 - precision: 0.9714 - recall: 0.9623 - val_accuracy: 0.9764 - val_auc: 0.9966 - val_loss: 682976.8125 - val_precision: 0.9908 - val_recall: 0.9600
Epoch 20/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9729 - auc: 0.9954 - loss: 0.0772 - precision: 0.9757 - recall: 0.9677 - val_accuracy: 0.9623 - val_auc: 0.9946 - val_loss: 766574144.0000 - val_precision: 0.9408 - val_recall: 0.9835
Epoch 21/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9706 - auc: 0.9948 - loss: 0.0841 - precision: 0.9731 - recall: 0.9656 - val_accuracy: 0.9719 - val_auc: 0.9927 - val_loss: 148986101760.0000 - val_precision: 0.9884 - val_recall: 0.9527
Epoch 22/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9743 - auc: 0.9952 - loss: 0.0773 - precision: 0.9761 - recall: 0.9703 - val_accuracy: 0.9770 - val_auc: 0.9932 - val_loss: 1316317184.0000 - val_precision: 0.9699 - val_recall: 0.9826
Epoch 23/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9773 - auc: 0.9959 - loss: 0.0704 - precision: 0.9791 - recall: 0.9735 - val_accuracy: 0.9452 - val_auc: 0.9862 - val_loss: 12898380800.0000 - val_precision: 0.9368 - val_recall: 0.9502
Epoch 24/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9774 - auc: 0.9958 - loss: 0.0700 - precision: 0.9795 - recall: 0.9734 - val_accuracy: 0.9583 - val_auc: 0.9898 - val_loss: 20892140.0000 - val_precision: 0.9408 - val_recall: 0.9745
Epoch 25/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9791 - auc: 0.9962 - loss: 0.0655 - precision: 0.9809 - recall: 0.9755 - val_accuracy: 0.9635 - val_auc: 0.9950 - val_loss: 132989935616.0000 - val_precision: 0.9914 - val_recall: 0.9323
Epoch 26/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9779 - auc: 0.9959 - loss: 0.0692 - precision: 0.9809 - recall: 0.9729 - val_accuracy: 0.9394 - val_auc: 0.9876 - val_loss: 38061128.0000 - val_precision: 0.9048 - val_recall: 0.9768
Epoch 27/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9786 - auc: 0.9962 - loss: 0.0658 - precision: 0.9810 - recall: 0.9745 - val_accuracy: 0.9782 - val_auc: 0.9943 - val_loss: 394034479104.0000 - val_precision: 0.9925 - val_recall: 0.9619
Epoch 28/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9773 - auc: 0.9958 - loss: 0.0701 - precision: 0.9793 - recall: 0.9734 - val_accuracy: 0.9626 - val_auc: 0.9899 - val_loss: 579255402496.0000 - val_precision: 0.9946 - val_recall: 0.9272
Epoch 29/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9771 - auc: 0.9958 - loss: 0.0708 - precision: 0.9794 - recall: 0.9729 - val_accuracy: 0.9789 - val_auc: 0.9947 - val_loss: 518762826563584.0000 - val_precision: 0.9858 - val_recall: 0.9701
Epoch 30/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9791 - auc: 0.9966 - loss: 0.0624 - precision: 0.9825 - recall: 0.9740 - val_accuracy: 0.9821 - val_auc: 0.9948 - val_loss: 165063917568.0000 - val_precision: 0.9873 - val_recall: 0.9754
Epoch 31/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9796 - auc: 0.9966 - loss: 0.0624 - precision: 0.9825 - recall: 0.9751 - val_accuracy: 0.9716 - val_auc: 0.9909 - val_loss: 14412241960960.0000 - val_precision: 0.9881 - val_recall: 0.9524
Epoch 32/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9715 - auc: 0.9942 - loss: 0.0856 - precision: 0.9747 - recall: 0.9659 - val_accuracy: 0.9723 - val_auc: 0.9855 - val_loss: 658064670720.0000 - val_precision: 0.9798 - val_recall: 0.9622
Epoch 33/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9768 - auc: 0.9953 - loss: 0.0756 - precision: 0.9792 - recall: 0.9724 - val_accuracy: 0.9719 - val_auc: 0.9925 - val_loss: 610580268318720.0000 - val_precision: 0.9858 - val_recall: 0.9552
Epoch 34/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9791 - auc: 0.9964 - loss: 0.0645 - precision: 0.9817 - recall: 0.9747 - val_accuracy: 0.9799 - val_auc: 0.9938 - val_loss: 476858474823680.0000 - val_precision: 0.9812 - val_recall: 0.9771
Epoch 35/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9781 - auc: 0.9961 - loss: 0.0666 - precision: 0.9809 - recall: 0.9735 - val_accuracy: 0.9756 - val_auc: 0.9936 - val_loss: 89310666752.0000 - val_precision: 0.9832 - val_recall: 0.9659
Epoch 36/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9794 - auc: 0.9964 - loss: 0.0635 - precision: 0.9820 - recall: 0.9750 - val_accuracy: 0.9744 - val_auc: 0.9909 - val_loss: 52432449044480.0000 - val_precision: 0.9944 - val_recall: 0.9521
Epoch 37/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9790 - auc: 0.9964 - loss: 0.0639 - precision: 0.9819 - recall: 0.9744 - val_accuracy: 0.9631 - val_auc: 0.9965 - val_loss: 662412032.0000 - val_precision: 0.9435 - val_recall: 0.9821
Epoch 38/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9791 - auc: 0.9966 - loss: 0.0625 - precision: 0.9821 - recall: 0.9743 - val_accuracy: 0.9663 - val_auc: 0.9962 - val_loss: 172529598464.0000 - val_precision: 0.9917 - val_recall: 0.9379
Epoch 39/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9766 - auc: 0.9960 - loss: 0.0709 - precision: 0.9792 - recall: 0.9720 - val_accuracy: 0.9821 - val_auc: 0.9933 - val_loss: 499975618560.0000 - val_precision: 0.9895 - val_recall: 0.9731
Epoch 40/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9794 - auc: 0.9969 - loss: 0.0607 - precision: 0.9816 - recall: 0.9754 - val_accuracy: 0.9768 - val_auc: 0.9938 - val_loss: 5634315264.0000 - val_precision: 0.9913 - val_recall: 0.9603
Epoch 41/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9788 - auc: 0.9966 - loss: 0.0626 - precision: 0.9808 - recall: 0.9751 - val_accuracy: 0.9705 - val_auc: 0.9948 - val_loss: 2207420252160.0000 - val_precision: 0.9523 - val_recall: 0.9882
Epoch 42/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9785 - auc: 0.9964 - loss: 0.0647 - precision: 0.9803 - recall: 0.9749 - val_accuracy: 0.9810 - val_auc: 0.9921 - val_loss: 18080082165760.0000 - val_precision: 0.9858 - val_recall: 0.9745
Epoch 43/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9802 - auc: 0.9969 - loss: 0.0594 - precision: 0.9818 - recall: 0.9769 - val_accuracy: 0.9820 - val_auc: 0.9942 - val_loss: 23467780096.0000 - val_precision: 0.9823 - val_recall: 0.9801
Epoch 44/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9804 - auc: 0.9969 - loss: 0.0586 - precision: 0.9827 - recall: 0.9765 - val_accuracy: 0.9829 - val_auc: 0.9929 - val_loss: 9163272880128.0000 - val_precision: 0.9878 - val_recall: 0.9765
Epoch 45/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9809 - auc: 0.9967 - loss: 0.0592 - precision: 0.9822 - recall: 0.9780 - val_accuracy: 0.9774 - val_auc: 0.9914 - val_loss: 729134144.0000 - val_precision: 0.9953 - val_recall: 0.9575
Epoch 46/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9814 - auc: 0.9971 - loss: 0.0557 - precision: 0.9834 - recall: 0.9779 - val_accuracy: 0.9830 - val_auc: 0.9960 - val_loss: 5624183652352.0000 - val_precision: 0.9931 - val_recall: 0.9715
Epoch 47/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9825 - auc: 0.9972 - loss: 0.0529 - precision: 0.9840 - recall: 0.9796 - val_accuracy: 0.9824 - val_auc: 0.9966 - val_loss: 17876555661312.0000 - val_precision: 0.9928 - val_recall: 0.9703
Epoch 48/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9836 - auc: 0.9974 - loss: 0.0514 - precision: 0.9850 - recall: 0.9810 - val_accuracy: 0.9756 - val_auc: 0.9932 - val_loss: 13292798976.0000 - val_precision: 0.9652 - val_recall: 0.9849
Epoch 49/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9796 - auc: 0.9969 - loss: 0.0607 - precision: 0.9814 - recall: 0.9760 - val_accuracy: 0.9781 - val_auc: 0.9933 - val_loss: 542709907456.0000 - val_precision: 0.9720 - val_recall: 0.9826
Epoch 50/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9818 - auc: 0.9971 - loss: 0.0550 - precision: 0.9840 - recall: 0.9781 - val_accuracy: 0.9840 - val_auc: 0.9948 - val_loss: 544700399616.0000 - val_precision: 0.9915 - val_recall: 0.9751
Epoch 51/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9801 - auc: 0.9951 - loss: 0.0835 - precision: 0.9813 - recall: 0.9774 - val_accuracy: 0.9846 - val_auc: 0.9955 - val_loss: 4475858190336.0000 - val_precision: 0.9868 - val_recall: 0.9812
Epoch 52/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9843 - auc: 0.9980 - loss: 0.0466 - precision: 0.9859 - recall: 0.9814 - val_accuracy: 0.9591 - val_auc: 0.9872 - val_loss: 365005614612480.0000 - val_precision: 0.9346 - val_recall: 0.9838
Epoch 53/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9816 - auc: 0.9971 - loss: 0.0567 - precision: 0.9831 - recall: 0.9785 - val_accuracy: 0.9830 - val_auc: 0.9938 - val_loss: 14342268387328.0000 - val_precision: 0.9923 - val_recall: 0.9723
Epoch 54/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9805 - auc: 0.9969 - loss: 0.0594 - precision: 0.9827 - recall: 0.9767 - val_accuracy: 0.9748 - val_auc: 0.9962 - val_loss: 9879302438912.0000 - val_precision: 0.9666 - val_recall: 0.9815
Epoch 55/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9824 - auc: 0.9973 - loss: 0.0533 - precision: 0.9843 - recall: 0.9790 - val_accuracy: 0.9838 - val_auc: 0.9962 - val_loss: 12504301305856.0000 - val_precision: 0.9917 - val_recall: 0.9745
Epoch 56/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9819 - auc: 0.9971 - loss: 0.0555 - precision: 0.9838 - recall: 0.9785 - val_accuracy: 0.9803 - val_auc: 0.9958 - val_loss: 21443599400960.0000 - val_precision: 0.9665 - val_recall: 0.9936
Epoch 57/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9820 - auc: 0.9972 - loss: 0.0538 - precision: 0.9837 - recall: 0.9788 - val_accuracy: 0.9840 - val_auc: 0.9958 - val_loss: 150421028995072.0000 - val_precision: 0.9954 - val_recall: 0.9712
Epoch 58/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9799 - auc: 0.9965 - loss: 0.0620 - precision: 0.9817 - recall: 0.9766 - val_accuracy: 0.9733 - val_auc: 0.9955 - val_loss: 71583079071744.0000 - val_precision: 0.9555 - val_recall: 0.9908
Epoch 59/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9828 - auc: 0.9972 - loss: 0.0532 - precision: 0.9842 - recall: 0.9801 - val_accuracy: 0.9779 - val_auc: 0.9949 - val_loss: 353221443584.0000 - val_precision: 0.9626 - val_recall: 0.9927
Epoch 60/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9831 - auc: 0.9973 - loss: 0.0524 - precision: 0.9845 - recall: 0.9803 - val_accuracy: 0.9810 - val_auc: 0.9933 - val_loss: 26276278566912.0000 - val_precision: 0.9769 - val_recall: 0.9838
Epoch 61/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9780 - auc: 0.9964 - loss: 0.0656 - precision: 0.9803 - recall: 0.9737 - val_accuracy: 0.9802 - val_auc: 0.9971 - val_loss: 25669463441408.0000 - val_precision: 0.9788 - val_recall: 0.9801
Epoch 62/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9821 - auc: 0.9970 - loss: 0.0568 - precision: 0.9838 - recall: 0.9788 - val_accuracy: 0.9860 - val_auc: 0.9956 - val_loss: 10993341382524928.0000 - val_precision: 0.9841 - val_recall: 0.9868
Epoch 63/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9826 - auc: 0.9970 - loss: 0.0556 - precision: 0.9839 - recall: 0.9799 - val_accuracy: 0.9774 - val_auc: 0.9951 - val_loss: 1265659350614016.0000 - val_precision: 0.9678 - val_recall: 0.9857
Epoch 64/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9833 - auc: 0.9974 - loss: 0.0513 - precision: 0.9848 - recall: 0.9805 - val_accuracy: 0.9811 - val_auc: 0.9963 - val_loss: 77688727404544.0000 - val_precision: 0.9730 - val_recall: 0.9882
Epoch 65/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9843 - auc: 0.9976 - loss: 0.0490 - precision: 0.9858 - recall: 0.9815 - val_accuracy: 0.9825 - val_auc: 0.9938 - val_loss: 1607072481280.0000 - val_precision: 0.9826 - val_recall: 0.9810
Epoch 66/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9833 - auc: 0.9976 - loss: 0.0497 - precision: 0.9849 - recall: 0.9803 - val_accuracy: 0.9803 - val_auc: 0.9942 - val_loss: 813072842752.0000 - val_precision: 0.9903 - val_recall: 0.9687
Epoch 67/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9821 - auc: 0.9968 - loss: 0.0583 - precision: 0.9836 - recall: 0.9791 - val_accuracy: 0.9817 - val_auc: 0.9933 - val_loss: 34167477764096.0000 - val_precision: 0.9892 - val_recall: 0.9726
Epoch 68/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9825 - auc: 0.9974 - loss: 0.0527 - precision: 0.9846 - recall: 0.9790 - val_accuracy: 0.9793 - val_auc: 0.9959 - val_loss: 11602087498481664.0000 - val_precision: 0.9652 - val_recall: 0.9927
Epoch 69/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9843 - auc: 0.9977 - loss: 0.0480 - precision: 0.9861 - recall: 0.9813 - val_accuracy: 0.9871 - val_auc: 0.9965 - val_loss: 6272131268608.0000 - val_precision: 0.9868 - val_recall: 0.9863
Epoch 70/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9835 - auc: 0.9977 - loss: 0.0496 - precision: 0.9854 - recall: 0.9802 - val_accuracy: 0.9840 - val_auc: 0.9948 - val_loss: 2249906978816.0000 - val_precision: 0.9881 - val_recall: 0.9784
Epoch 71/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9841 - auc: 0.9976 - loss: 0.0487 - precision: 0.9860 - recall: 0.9810 - val_accuracy: 0.9852 - val_auc: 0.9926 - val_loss: 17185891155968.0000 - val_precision: 0.9929 - val_recall: 0.9762
Epoch 72/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9852 - auc: 0.9980 - loss: 0.0439 - precision: 0.9865 - recall: 0.9828 - val_accuracy: 0.9844 - val_auc: 0.9941 - val_loss: 44269002752.0000 - val_precision: 0.9912 - val_recall: 0.9762
Epoch 73/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9850 - auc: 0.9978 - loss: 0.0457 - precision: 0.9865 - recall: 0.9822 - val_accuracy: 0.9864 - val_auc: 0.9948 - val_loss: 151954634309632.0000 - val_precision: 0.9932 - val_recall: 0.9784
Epoch 74/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9842 - auc: 0.9973 - loss: 0.0510 - precision: 0.9852 - recall: 0.9819 - val_accuracy: 0.9833 - val_auc: 0.9920 - val_loss: 170247168458752.0000 - val_precision: 0.9832 - val_recall: 0.9821
Epoch 75/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9833 - auc: 0.9979 - loss: 0.0479 - precision: 0.9852 - recall: 0.9800 - val_accuracy: 0.9810 - val_auc: 0.9924 - val_loss: 15834363723776.0000 - val_precision: 0.9812 - val_recall: 0.9793
Epoch 76/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9829 - auc: 0.9976 - loss: 0.0506 - precision: 0.9844 - recall: 0.9799 - val_accuracy: 0.9833 - val_auc: 0.9932 - val_loss: 18068568784502784.0000 - val_precision: 0.9929 - val_recall: 0.9723
Epoch 77/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9837 - auc: 0.9978 - loss: 0.0480 - precision: 0.9856 - recall: 0.9805 - val_accuracy: 0.9851 - val_auc: 0.9968 - val_loss: 279422271488.0000 - val_precision: 0.9868 - val_recall: 0.9821
Epoch 78/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9845 - auc: 0.9979 - loss: 0.0463 - precision: 0.9862 - recall: 0.9815 - val_accuracy: 0.9810 - val_auc: 0.9944 - val_loss: 2969123684352.0000 - val_precision: 0.9709 - val_recall: 0.9902
Epoch 79/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9852 - auc: 0.9979 - loss: 0.0444 - precision: 0.9867 - recall: 0.9825 - val_accuracy: 0.9785 - val_auc: 0.9892 - val_loss: 143995774697472.0000 - val_precision: 0.9855 - val_recall: 0.9695
Epoch 80/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9850 - auc: 0.9979 - loss: 0.0448 - precision: 0.9863 - recall: 0.9826 - val_accuracy: 0.9781 - val_auc: 0.9899 - val_loss: 125182853251072.0000 - val_precision: 0.9833 - val_recall: 0.9709
Epoch 81/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9838 - auc: 0.9970 - loss: 0.0568 - precision: 0.9852 - recall: 0.9811 - val_accuracy: 0.9863 - val_auc: 0.9961 - val_loss: 156466413568000.0000 - val_precision: 0.9951 - val_recall: 0.9762
Epoch 82/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9831 - auc: 0.9962 - loss: 0.0797 - precision: 0.9850 - recall: 0.9798 - val_accuracy: 0.9845 - val_auc: 0.9956 - val_loss: 97245617717248.0000 - val_precision: 0.9923 - val_recall: 0.9754
Epoch 83/200
2205/2205 - 6s - 3ms/step - accuracy: 0.9859 - auc: 0.9984 - loss: 0.0417 - precision: 0.9877 - recall: 0.9829 - val_accuracy: 0.9840 - val_auc: 0.9975 - val_loss: 225877803008.0000 - val_precision: 0.9737 - val_recall: 0.9936
Epoch 84/200

In [158]:
y_probability = model.predict(
    X_test,
    verbose=0,
).reshape(-1)

y_pred = (y_probability >= 0.5).astype(np.int32)
y_test_int = y_test.astype(np.int32)

In [159]:
cm = confusion_matrix(y_test_int, y_pred)
tn, fp, fn, tp = cm.ravel()

accuracy = accuracy_score(y_test_int, y_pred)

recall = recall_score(
    y_test_int,
    y_pred,
    pos_label=1,
    zero_division=0,
)

precision = precision_score(
    y_test_int,
    y_pred,
    pos_label=1,
    zero_division=0,
)



false_positive_rate = (
    fp / (fp + tn)
    if (fp + tn) > 0
    else 0.0
)

f1 = f1_score(
    y_test_int,
    y_pred,
    pos_label=1,
    zero_division=0,
)


print("Confusion matrix")
print("----------------")
print(cm)

print("\nAttack-class metrics")
print("--------------------")
print(f"Accuracy : {accuracy:.4f} "
      f"({accuracy * 100:.2f}%)")
print(f"Detection rate : {recall:.4f} "
      f"({recall * 100:.2f}%)")
print(f"Precision      : {precision:.4f} "
      f"({precision * 100:.2f}%)")
print(f"FPR            : {false_positive_rate:.4f} "
      f"({false_positive_rate * 100:.2f}%)")
print(f"F1 score       : {f1:.4f} "
      f"({f1 * 100:.2f}%)")

Confusion matrix
----------------
[[ 9461   250]
 [  342 12491]]

Attack-class metrics
--------------------
Accuracy : 0.9737 (97.37%)
Detection rate : 0.9733 (97.33%)
Precision      : 0.9804 (98.04%)
FPR            : 0.0257 (2.57%)
F1 score       : 0.9769 (97.69%)

In [ ]:
model.save("/content/drive/MyDrive/Models_Table_5/DNN_Vinayakumar.keras")

# **Attack classification of an intrusion detection system using deep learning and hyperparameter optimization [31]**

In [ ]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

VALIDATION_SIZE = 0.20
BATCH_SIZE = 256
LEARNING_RATE = 0.01
DAE_EPOCHS = 100
DNN_EPOCHS = 200

In [ ]:
NUMBER_OF_FEATURES = 122
NUMBER_OF_CLASSES = 5

CLASS_NAMES = [
    "Normal",
    "DoS",
    "Probe",
    "R2L",
    "U2R",
]

FEATURE_COLUMNS = column_names[:41]
CATEGORICAL_COLUMNS = [
    "protocol_type",
    "service",
    "flag",
]

NUMERICAL_COLUMNS = [
    column
    for column in FEATURE_COLUMNS
    if column not in CATEGORICAL_COLUMNS
]

In [ ]:
ATTACK_GROUPS = {
    "Normal": {
        "normal",
    },

    "DoS": {
        "apache2",
        "back",
        "mailbomb",
        "processtable",
        "teardrop",
        "smurf",
        "land",
        "neptune",
        "pod",
        "udpstorm",
    },

    "Probe": {
        "nmap",
        "ipsweep",
        "portsweep",
        "satan",
        "mscan",
        "saint",
    },

    "R2L": {
        "ftp_write",
        "guess_passwd",
        "snmpgetattack",
        "snmpguess",
        "imap",
        "spy",
        "warezclient",
        "warezmaster",
        "multihop",
        "phf",
        "named",
        "sendmail",
        "xlock",
        "xsnoop",
        "worm",
    },

    "U2R": {
        "ps",
        "buffer_overflow",
        "perl",
        "rootkit",
        "loadmodule",
        "xterm",
        "sqlattack",
        "httptunnel",
    },
}


ATTACK_TO_CLASS = {
    attack_name: class_name
    for class_name, attack_names in ATTACK_GROUPS.items()
    for attack_name in attack_names
}

CLASS_TO_INDEX = {
    class_name: index
    for index, class_name in enumerate(CLASS_NAMES)
}

In [ ]:
train_attack_names = (
    train_df["label"]
    .astype(str)
    .str.strip()
    .str.rstrip(".")
    .str.lower()
)

test_attack_names = (
    test_df["label"]
    .astype(str)
    .str.strip()
    .str.rstrip(".")
    .str.lower()
)

In [ ]:
train_class_names = train_attack_names.map(ATTACK_TO_CLASS)
test_class_names = test_attack_names.map(ATTACK_TO_CLASS)

y_train_all = (
    train_class_names
    .map(CLASS_TO_INDEX)
    .to_numpy(dtype=np.int32)
)

y_test = (
    test_class_names
    .map(CLASS_TO_INDEX)
    .to_numpy(dtype=np.int32)
)

In [ ]:
X_train_df = train_df[FEATURE_COLUMNS].copy()
X_test_df = test_df[FEATURE_COLUMNS].copy()

In [ ]:
categorical_encoder = OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=False,
        dtype=np.float32,
    )

X_train_categorical = categorical_encoder.fit_transform(
    X_train_df[CATEGORICAL_COLUMNS]
)

X_test_categorical = categorical_encoder.transform(
    X_test_df[CATEGORICAL_COLUMNS]
)



X_train_numerical = (
    X_train_df[NUMERICAL_COLUMNS]
    .astype(np.float32)
    .to_numpy()
)

X_test_numerical = (
    X_test_df[NUMERICAL_COLUMNS]
    .astype(np.float32)
    .to_numpy()
)



X_train_all = np.concatenate(
    [
        X_train_numerical,
        X_train_categorical,
    ],
    axis=1,
)

X_test = np.concatenate(
    [
        X_test_numerical,
        X_test_categorical,
    ],
    axis=1,
).astype(np.float32)

In [ ]:
scaler = MinMaxScaler(
        feature_range=(0.0, 1.0),
        clip=True,
    )

X_train_all = scaler.fit_transform(
    X_train_all
).astype(np.float32)

X_test = scaler.transform(
    X_test
).astype(np.float32)

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(
    X_train_all,
    y_train_all,
    test_size=VALIDATION_SIZE,
    random_state=SEED,
    stratify=y_train_all,
)


# One-hot encode the five output classes

y_train_encoded = tf.keras.utils.to_categorical(
    y_train,
    num_classes=NUMBER_OF_CLASSES,
).astype(np.float32)

y_val_encoded = tf.keras.utils.to_categorical(
    y_val,
    num_classes=NUMBER_OF_CLASSES,
).astype(np.float32)

y_test_encoded = tf.keras.utils.to_categorical(
    y_test,
    num_classes=NUMBER_OF_CLASSES,
).astype(np.float32)

In [ ]:
autoencoder_input = tf.keras.layers.Input(
    shape=(NUMBER_OF_FEATURES,),
    name="autoencoder_input",
)

encoder_100 = tf.keras.layers.Dense(
    units=100,
    activation="relu",
    kernel_initializer="he_uniform",
    name="encoder_100",
)(autoencoder_input)

bottleneck_20 = tf.keras.layers.Dense(
    units=20,
    activation="relu",
    kernel_initializer="he_uniform",
    name="bottleneck_20",
)(encoder_100)

decoder_100 = tf.keras.layers.Dense(
    units=100,
    activation="relu",
    kernel_initializer="he_uniform",
    name="decoder_100",
)(bottleneck_20)

reconstruction_output = tf.keras.layers.Dense(
    units=NUMBER_OF_FEATURES,
    activation="sigmoid",
    kernel_initializer="he_uniform",
    name="reconstruction_output",
)(decoder_100)

autoencoder = tf.keras.Model(
    inputs=autoencoder_input,
    outputs=reconstruction_output,
    name="nsl_kdd_deep_autoencoder",
)

autoencoder.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=LEARNING_RATE,
    ),
    loss=tf.keras.losses.BinaryCrossentropy(),
)

print("\nDeep autoencoder")
print("----------------")
autoencoder.summary()

Deep autoencoder
----------------

Model: "nsl_kdd_deep_autoencoder"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ autoencoder_input (InputLayer)  │ (None, 122)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ encoder_100 (Dense)             │ (None, 100)            │        12,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bottleneck_20 (Dense)           │ (None, 20)             │         2,020 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ decoder_100 (Dense)             │ (None, 100)            │         2,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reconstruction_output (Dense)   │ (None, 122)            │        12,322 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 28,742 (112.27 KB)

 Trainable params: 28,742 (112.27 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
dae_history = autoencoder.fit(
    X_train,
    X_train,
    validation_data=(X_val, X_val),
    epochs=DAE_EPOCHS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    verbose=2,
)

Epoch 1/100
394/394 - 37s - 93ms/step - loss: 0.0347 - val_loss: 0.0160
Epoch 2/100
394/394 - 1s - 2ms/step - loss: 0.0154 - val_loss: 0.0151
Epoch 3/100
394/394 - 1s - 2ms/step - loss: 0.0148 - val_loss: 0.0147
Epoch 4/100
394/394 - 1s - 2ms/step - loss: 0.0145 - val_loss: 0.0145
Epoch 5/100
394/394 - 1s - 2ms/step - loss: 0.0144 - val_loss: 0.0144
Epoch 6/100
394/394 - 1s - 2ms/step - loss: 0.0143 - val_loss: 0.0144
Epoch 7/100
394/394 - 1s - 2ms/step - loss: 0.0142 - val_loss: 0.0144
Epoch 8/100
394/394 - 1s - 2ms/step - loss: 0.0142 - val_loss: 0.0142
Epoch 9/100
394/394 - 1s - 2ms/step - loss: 0.0141 - val_loss: 0.0142
Epoch 10/100
394/394 - 1s - 2ms/step - loss: 0.0141 - val_loss: 0.0141
Epoch 11/100
394/394 - 1s - 2ms/step - loss: 0.0141 - val_loss: 0.0142
Epoch 12/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0142
Epoch 13/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0140
Epoch 14/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0141
Epoch 15/100
394/394 - 1s - 2ms/step - loss: 0.0141 - val_loss: 0.0143
Epoch 16/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0142
Epoch 17/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0140
Epoch 18/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0140
Epoch 19/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 20/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0143
Epoch 21/100
394/394 - 1s - 2ms/step - loss: 0.0141 - val_loss: 0.0143
Epoch 22/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0141
Epoch 23/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 24/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0142
Epoch 25/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 26/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 27/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0141
Epoch 28/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0140
Epoch 29/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 30/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0141
Epoch 31/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0141
Epoch 32/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 33/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0142
Epoch 34/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 35/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0144
Epoch 36/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0140
Epoch 37/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140
Epoch 38/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140
Epoch 39/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0141
Epoch 40/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0143
Epoch 41/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0141
Epoch 42/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0142
Epoch 43/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140
Epoch 44/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0144
Epoch 45/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0141
Epoch 46/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 47/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0142
Epoch 48/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0139
Epoch 49/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0142
Epoch 50/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0141
Epoch 51/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0141
Epoch 52/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 53/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0139
Epoch 54/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140
Epoch 55/100
394/394 - 1s - 2ms/step - loss: 0.0141 - val_loss: 0.0141
Epoch 56/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0140
Epoch 57/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140
Epoch 58/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140
Epoch 59/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0141
Epoch 60/100
394/394 - 1s - 2ms/step - loss: 0.0142 - val_loss: 0.0142
Epoch 61/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 62/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0142
Epoch 63/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0142
Epoch 64/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140
Epoch 65/100
394/394 - 1s - 2ms/step - loss: 0.0137 - val_loss: 0.0139
Epoch 66/100
394/394 - 1s - 2ms/step - loss: 0.0141 - val_loss: 0.0143
Epoch 67/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0142
Epoch 68/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0141
Epoch 69/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0139
Epoch 70/100
394/394 - 1s - 2ms/step - loss: 0.0142 - val_loss: 0.0142
Epoch 71/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140
Epoch 72/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0141
Epoch 73/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0142
Epoch 74/100
394/394 - 1s - 2ms/step - loss: 0.0141 - val_loss: 0.0142
Epoch 75/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 76/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0141
Epoch 77/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0139
Epoch 78/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140
Epoch 79/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0143
Epoch 80/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0142
Epoch 81/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0144
Epoch 82/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0141
Epoch 83/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0142
Epoch 84/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0139
Epoch 85/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0141
Epoch 86/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0139
Epoch 87/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0141
Epoch 88/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0146
Epoch 89/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0140
Epoch 90/100
394/394 - 1s - 2ms/step - loss: 0.0137 - val_loss: 0.0143
Epoch 91/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0141
Epoch 92/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 93/100
394/394 - 1s - 2ms/step - loss: 0.0140 - val_loss: 0.0141
Epoch 94/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140
Epoch 95/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0139
Epoch 96/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0145
Epoch 97/100
394/394 - 1s - 2ms/step - loss: 0.0143 - val_loss: 0.0141
Epoch 98/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140
Epoch 99/100
394/394 - 1s - 2ms/step - loss: 0.0139 - val_loss: 0.0140
Epoch 100/100
394/394 - 1s - 2ms/step - loss: 0.0138 - val_loss: 0.0140

In [ ]:
classifier = tf.keras.Sequential(
    [
        tf.keras.layers.Input(
            shape=(NUMBER_OF_FEATURES,),
            name="classifier_input",
        ),

        tf.keras.layers.Dense(
            units=100,
            activation="relu",
            kernel_initializer="he_uniform",
            name="classifier_encoder_100",
        ),

        tf.keras.layers.Dense(
            units=20,
            activation="relu",
            kernel_initializer="he_uniform",
            name="classifier_bottleneck_20",
        ),

        tf.keras.layers.Dense(
            units=NUMBER_OF_CLASSES,
            activation="softmax",
            kernel_initializer="he_uniform",
            name="multiclass_output",
        ),
    ],
    name="nsl_kdd_ptdae_dnn",
)



_ = classifier(
    np.zeros(
        (1, NUMBER_OF_FEATURES),
        dtype=np.float32,
    )
)

In [ ]:
classifier.get_layer(
    "classifier_encoder_100"
).set_weights(
    autoencoder.get_layer(
        "encoder_100"
    ).get_weights()
)

classifier.get_layer(
    "classifier_bottleneck_20"
).set_weights(
    autoencoder.get_layer(
        "bottleneck_20"
    ).get_weights()
)



classifier.get_layer(
    "classifier_encoder_100"
).trainable = True

classifier.get_layer(
    "classifier_bottleneck_20"
).trainable = True

In [ ]:
classifier.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=LEARNING_RATE,
    ),
    loss=tf.keras.losses.CategoricalCrossentropy(),
    metrics=[
        tf.keras.metrics.CategoricalAccuracy(
            name="accuracy",
        ),
    ],
)

classifier.summary()

Model: "nsl_kdd_ptdae_dnn"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ classifier_encoder_100 (Dense)  │ (None, 100)            │        12,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ classifier_bottleneck_20        │ (None, 20)             │         2,020 │
│ (Dense)                         │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ multiclass_output (Dense)       │ (None, 5)              │           105 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14,425 (56.35 KB)

 Trainable params: 14,425 (56.35 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
dnn_history = classifier.fit(
    X_train,
    y_train_encoded,
    validation_data=(
        X_val,
        y_val_encoded,
    ),
    epochs=DNN_EPOCHS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    verbose=2,
)

Epoch 1/200
394/394 - 9s - 22ms/step - accuracy: 0.9684 - loss: 0.1041 - val_accuracy: 0.9869 - val_loss: 0.0351
Epoch 2/200
394/394 - 1s - 2ms/step - accuracy: 0.9915 - loss: 0.0256 - val_accuracy: 0.9899 - val_loss: 0.0259
Epoch 3/200
394/394 - 1s - 2ms/step - accuracy: 0.9934 - loss: 0.0197 - val_accuracy: 0.9900 - val_loss: 0.0242
Epoch 4/200
394/394 - 1s - 2ms/step - accuracy: 0.9941 - loss: 0.0171 - val_accuracy: 0.9902 - val_loss: 0.0242
Epoch 5/200
394/394 - 1s - 2ms/step - accuracy: 0.9945 - loss: 0.0158 - val_accuracy: 0.9906 - val_loss: 0.0241
Epoch 6/200
394/394 - 1s - 2ms/step - accuracy: 0.9950 - loss: 0.0148 - val_accuracy: 0.9923 - val_loss: 0.0207
Epoch 7/200
394/394 - 1s - 2ms/step - accuracy: 0.9954 - loss: 0.0136 - val_accuracy: 0.9933 - val_loss: 0.0199
Epoch 8/200
394/394 - 1s - 2ms/step - accuracy: 0.9955 - loss: 0.0134 - val_accuracy: 0.9919 - val_loss: 0.0227
Epoch 9/200
394/394 - 1s - 2ms/step - accuracy: 0.9957 - loss: 0.0126 - val_accuracy: 0.9926 - val_loss: 0.0221
Epoch 10/200
394/394 - 1s - 2ms/step - accuracy: 0.9958 - loss: 0.0122 - val_accuracy: 0.9927 - val_loss: 0.0216
Epoch 11/200
394/394 - 1s - 2ms/step - accuracy: 0.9960 - loss: 0.0116 - val_accuracy: 0.9940 - val_loss: 0.0193
Epoch 12/200
394/394 - 1s - 2ms/step - accuracy: 0.9962 - loss: 0.0114 - val_accuracy: 0.9941 - val_loss: 0.0177
Epoch 13/200
394/394 - 1s - 2ms/step - accuracy: 0.9962 - loss: 0.0110 - val_accuracy: 0.9941 - val_loss: 0.0185
Epoch 14/200
394/394 - 1s - 2ms/step - accuracy: 0.9965 - loss: 0.0106 - val_accuracy: 0.9948 - val_loss: 0.0185
Epoch 15/200
394/394 - 1s - 2ms/step - accuracy: 0.9964 - loss: 0.0104 - val_accuracy: 0.9953 - val_loss: 0.0170
Epoch 16/200
394/394 - 1s - 2ms/step - accuracy: 0.9965 - loss: 0.0101 - val_accuracy: 0.9946 - val_loss: 0.0181
Epoch 17/200
394/394 - 1s - 2ms/step - accuracy: 0.9966 - loss: 0.0100 - val_accuracy: 0.9942 - val_loss: 0.0187
Epoch 18/200
394/394 - 1s - 2ms/step - accuracy: 0.9964 - loss: 0.0106 - val_accuracy: 0.9925 - val_loss: 0.0220
Epoch 19/200
394/394 - 1s - 2ms/step - accuracy: 0.9965 - loss: 0.0103 - val_accuracy: 0.9941 - val_loss: 0.0200
Epoch 20/200
394/394 - 1s - 2ms/step - accuracy: 0.9965 - loss: 0.0096 - val_accuracy: 0.9933 - val_loss: 0.0212
Epoch 21/200
394/394 - 1s - 2ms/step - accuracy: 0.9968 - loss: 0.0092 - val_accuracy: 0.9929 - val_loss: 0.0222
Epoch 22/200
394/394 - 1s - 2ms/step - accuracy: 0.9969 - loss: 0.0092 - val_accuracy: 0.9949 - val_loss: 0.0181
Epoch 23/200
394/394 - 1s - 2ms/step - accuracy: 0.9969 - loss: 0.0092 - val_accuracy: 0.9950 - val_loss: 0.0179
Epoch 24/200
394/394 - 1s - 3ms/step - accuracy: 0.9968 - loss: 0.0092 - val_accuracy: 0.9948 - val_loss: 0.0192
Epoch 25/200
394/394 - 1s - 2ms/step - accuracy: 0.9969 - loss: 0.0090 - val_accuracy: 0.9952 - val_loss: 0.0190
Epoch 26/200
394/394 - 1s - 2ms/step - accuracy: 0.9969 - loss: 0.0089 - val_accuracy: 0.9953 - val_loss: 0.0191
Epoch 27/200
394/394 - 1s - 2ms/step - accuracy: 0.9969 - loss: 0.0082 - val_accuracy: 0.9943 - val_loss: 0.0204
Epoch 28/200
394/394 - 1s - 2ms/step - accuracy: 0.9968 - loss: 0.0088 - val_accuracy: 0.9946 - val_loss: 0.0212
Epoch 29/200
394/394 - 1s - 2ms/step - accuracy: 0.9969 - loss: 0.0094 - val_accuracy: 0.9950 - val_loss: 0.0190
Epoch 30/200
394/394 - 1s - 2ms/step - accuracy: 0.9968 - loss: 0.0093 - val_accuracy: 0.9950 - val_loss: 0.0209
Epoch 31/200
394/394 - 1s - 2ms/step - accuracy: 0.9970 - loss: 0.0084 - val_accuracy: 0.9950 - val_loss: 0.0201
Epoch 32/200
394/394 - 1s - 2ms/step - accuracy: 0.9972 - loss: 0.0081 - val_accuracy: 0.9952 - val_loss: 0.0183
Epoch 33/200
394/394 - 1s - 2ms/step - accuracy: 0.9970 - loss: 0.0083 - val_accuracy: 0.9954 - val_loss: 0.0191
Epoch 34/200
394/394 - 1s - 2ms/step - accuracy: 0.9969 - loss: 0.0087 - val_accuracy: 0.9943 - val_loss: 0.0219
Epoch 35/200
394/394 - 1s - 2ms/step - accuracy: 0.9970 - loss: 0.0088 - val_accuracy: 0.9951 - val_loss: 0.0206
Epoch 36/200
394/394 - 1s - 2ms/step - accuracy: 0.9973 - loss: 0.0078 - val_accuracy: 0.9953 - val_loss: 0.0198
Epoch 37/200
394/394 - 1s - 2ms/step - accuracy: 0.9972 - loss: 0.0081 - val_accuracy: 0.9958 - val_loss: 0.0186
Epoch 38/200
394/394 - 1s - 2ms/step - accuracy: 0.9974 - loss: 0.0075 - val_accuracy: 0.9954 - val_loss: 0.0184
Epoch 39/200
394/394 - 1s - 2ms/step - accuracy: 0.9972 - loss: 0.0074 - val_accuracy: 0.9953 - val_loss: 0.0201
Epoch 40/200
394/394 - 1s - 2ms/step - accuracy: 0.9973 - loss: 0.0076 - val_accuracy: 0.9955 - val_loss: 0.0189
Epoch 41/200
394/394 - 1s - 2ms/step - accuracy: 0.9973 - loss: 0.0076 - val_accuracy: 0.9952 - val_loss: 0.0198
Epoch 42/200
394/394 - 1s - 2ms/step - accuracy: 0.9973 - loss: 0.0075 - val_accuracy: 0.9956 - val_loss: 0.0205
Epoch 43/200
394/394 - 1s - 2ms/step - accuracy: 0.9972 - loss: 0.0081 - val_accuracy: 0.9953 - val_loss: 0.0190
Epoch 44/200
394/394 - 1s - 2ms/step - accuracy: 0.9974 - loss: 0.0073 - val_accuracy: 0.9954 - val_loss: 0.0190
Epoch 45/200
394/394 - 1s - 2ms/step - accuracy: 0.9974 - loss: 0.0074 - val_accuracy: 0.9960 - val_loss: 0.0183
Epoch 46/200
394/394 - 1s - 2ms/step - accuracy: 0.9974 - loss: 0.0072 - val_accuracy: 0.9954 - val_loss: 0.0188
Epoch 47/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0067 - val_accuracy: 0.9953 - val_loss: 0.0204
Epoch 48/200
394/394 - 1s - 2ms/step - accuracy: 0.9975 - loss: 0.0077 - val_accuracy: 0.9958 - val_loss: 0.0185
Epoch 49/200
394/394 - 1s - 2ms/step - accuracy: 0.9975 - loss: 0.0068 - val_accuracy: 0.9959 - val_loss: 0.0189
Epoch 50/200
394/394 - 1s - 2ms/step - accuracy: 0.9974 - loss: 0.0071 - val_accuracy: 0.9958 - val_loss: 0.0185
Epoch 51/200
394/394 - 1s - 2ms/step - accuracy: 0.9975 - loss: 0.0067 - val_accuracy: 0.9960 - val_loss: 0.0209
Epoch 52/200
394/394 - 1s - 2ms/step - accuracy: 0.9969 - loss: 0.0086 - val_accuracy: 0.9958 - val_loss: 0.0199
Epoch 53/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0066 - val_accuracy: 0.9961 - val_loss: 0.0185
Epoch 54/200
394/394 - 1s - 2ms/step - accuracy: 0.9977 - loss: 0.0062 - val_accuracy: 0.9959 - val_loss: 0.0195
Epoch 55/200
394/394 - 1s - 2ms/step - accuracy: 0.9975 - loss: 0.0071 - val_accuracy: 0.9946 - val_loss: 0.0216
Epoch 56/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0069 - val_accuracy: 0.9954 - val_loss: 0.0200
Epoch 57/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0067 - val_accuracy: 0.9955 - val_loss: 0.0197
Epoch 58/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0064 - val_accuracy: 0.9959 - val_loss: 0.0198
Epoch 59/200
394/394 - 1s - 2ms/step - accuracy: 0.9974 - loss: 0.0070 - val_accuracy: 0.9957 - val_loss: 0.0195
Epoch 60/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0066 - val_accuracy: 0.9963 - val_loss: 0.0186
Epoch 61/200
394/394 - 1s - 2ms/step - accuracy: 0.9977 - loss: 0.0062 - val_accuracy: 0.9960 - val_loss: 0.0190
Epoch 62/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0061 - val_accuracy: 0.9956 - val_loss: 0.0202
Epoch 63/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0066 - val_accuracy: 0.9960 - val_loss: 0.0204
Epoch 64/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0073 - val_accuracy: 0.9960 - val_loss: 0.0226
Epoch 65/200
394/394 - 1s - 2ms/step - accuracy: 0.9974 - loss: 0.0079 - val_accuracy: 0.9960 - val_loss: 0.0238
Epoch 66/200
394/394 - 1s - 2ms/step - accuracy: 0.9977 - loss: 0.0066 - val_accuracy: 0.9966 - val_loss: 0.0193
Epoch 67/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0062 - val_accuracy: 0.9960 - val_loss: 0.0237
Epoch 68/200
394/394 - 1s - 2ms/step - accuracy: 0.9977 - loss: 0.0065 - val_accuracy: 0.9963 - val_loss: 0.0225
Epoch 69/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0066 - val_accuracy: 0.9962 - val_loss: 0.0235
Epoch 70/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0059 - val_accuracy: 0.9962 - val_loss: 0.0247
Epoch 71/200
394/394 - 1s - 2ms/step - accuracy: 0.9977 - loss: 0.0065 - val_accuracy: 0.9959 - val_loss: 0.0252
Epoch 72/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0060 - val_accuracy: 0.9965 - val_loss: 0.0224
Epoch 73/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0057 - val_accuracy: 0.9959 - val_loss: 0.0229
Epoch 74/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0069 - val_accuracy: 0.9952 - val_loss: 0.0243
Epoch 75/200
394/394 - 1s - 2ms/step - accuracy: 0.9977 - loss: 0.0060 - val_accuracy: 0.9959 - val_loss: 0.0221
Epoch 76/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0057 - val_accuracy: 0.9960 - val_loss: 0.0236
Epoch 77/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0061 - val_accuracy: 0.9958 - val_loss: 0.0229
Epoch 78/200
394/394 - 1s - 2ms/step - accuracy: 0.9974 - loss: 0.0065 - val_accuracy: 0.9959 - val_loss: 0.0221
Epoch 79/200
394/394 - 1s - 2ms/step - accuracy: 0.9975 - loss: 0.0079 - val_accuracy: 0.9964 - val_loss: 0.0245
Epoch 80/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0062 - val_accuracy: 0.9963 - val_loss: 0.0259
Epoch 81/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0062 - val_accuracy: 0.9960 - val_loss: 0.0248
Epoch 82/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0058 - val_accuracy: 0.9961 - val_loss: 0.0261
Epoch 83/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0063 - val_accuracy: 0.9964 - val_loss: 0.0241
Epoch 84/200
394/394 - 1s - 2ms/step - accuracy: 0.9977 - loss: 0.0056 - val_accuracy: 0.9963 - val_loss: 0.0239
Epoch 85/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0064 - val_accuracy: 0.9964 - val_loss: 0.0226
Epoch 86/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0062 - val_accuracy: 0.9961 - val_loss: 0.0247
Epoch 87/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0057 - val_accuracy: 0.9963 - val_loss: 0.0240
Epoch 88/200
394/394 - 1s - 2ms/step - accuracy: 0.9977 - loss: 0.0063 - val_accuracy: 0.9960 - val_loss: 0.0272
Epoch 89/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0059 - val_accuracy: 0.9968 - val_loss: 0.0254
Epoch 90/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0057 - val_accuracy: 0.9958 - val_loss: 0.0232
Epoch 91/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0055 - val_accuracy: 0.9963 - val_loss: 0.0238
Epoch 92/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0053 - val_accuracy: 0.9964 - val_loss: 0.0239
Epoch 93/200
394/394 - 1s - 2ms/step - accuracy: 0.9977 - loss: 0.0062 - val_accuracy: 0.9962 - val_loss: 0.0282
Epoch 94/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0059 - val_accuracy: 0.9961 - val_loss: 0.0273
Epoch 95/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0073 - val_accuracy: 0.9960 - val_loss: 0.0249
Epoch 96/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0068 - val_accuracy: 0.9967 - val_loss: 0.0203
Epoch 97/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0055 - val_accuracy: 0.9960 - val_loss: 0.0237
Epoch 98/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0052 - val_accuracy: 0.9962 - val_loss: 0.0240
Epoch 99/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0055 - val_accuracy: 0.9962 - val_loss: 0.0238
Epoch 100/200
394/394 - 1s - 2ms/step - accuracy: 0.9975 - loss: 0.0071 - val_accuracy: 0.9957 - val_loss: 0.0241
Epoch 101/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0059 - val_accuracy: 0.9962 - val_loss: 0.0229
Epoch 102/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0062 - val_accuracy: 0.9959 - val_loss: 0.0276
Epoch 103/200
394/394 - 1s - 2ms/step - accuracy: 0.9975 - loss: 0.0067 - val_accuracy: 0.9955 - val_loss: 0.0273
Epoch 104/200
394/394 - 1s - 2ms/step - accuracy: 0.9977 - loss: 0.0060 - val_accuracy: 0.9962 - val_loss: 0.0268
Epoch 105/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0056 - val_accuracy: 0.9963 - val_loss: 0.0263
Epoch 106/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0053 - val_accuracy: 0.9963 - val_loss: 0.0281
Epoch 107/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0059 - val_accuracy: 0.9963 - val_loss: 0.0306
Epoch 108/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0056 - val_accuracy: 0.9964 - val_loss: 0.0276
Epoch 109/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0057 - val_accuracy: 0.9954 - val_loss: 0.0296
Epoch 110/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0057 - val_accuracy: 0.9965 - val_loss: 0.0263
Epoch 111/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0065 - val_accuracy: 0.9962 - val_loss: 0.0277
Epoch 112/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0056 - val_accuracy: 0.9965 - val_loss: 0.0257
Epoch 113/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0054 - val_accuracy: 0.9962 - val_loss: 0.0279
Epoch 114/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0053 - val_accuracy: 0.9963 - val_loss: 0.0273
Epoch 115/200
394/394 - 1s - 2ms/step - accuracy: 0.9977 - loss: 0.0061 - val_accuracy: 0.9963 - val_loss: 0.0271
Epoch 116/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0059 - val_accuracy: 0.9958 - val_loss: 0.0273
Epoch 117/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0052 - val_accuracy: 0.9959 - val_loss: 0.0273
Epoch 118/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0052 - val_accuracy: 0.9958 - val_loss: 0.0278
Epoch 119/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0056 - val_accuracy: 0.9962 - val_loss: 0.0287
Epoch 120/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0052 - val_accuracy: 0.9961 - val_loss: 0.0309
Epoch 121/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0056 - val_accuracy: 0.9961 - val_loss: 0.0319
Epoch 122/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0064 - val_accuracy: 0.9962 - val_loss: 0.0305
Epoch 123/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0057 - val_accuracy: 0.9966 - val_loss: 0.0282
Epoch 124/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0050 - val_accuracy: 0.9963 - val_loss: 0.0301
Epoch 125/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0052 - val_accuracy: 0.9958 - val_loss: 0.0311
Epoch 126/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0051 - val_accuracy: 0.9965 - val_loss: 0.0324
Epoch 127/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0053 - val_accuracy: 0.9962 - val_loss: 0.0316
Epoch 128/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0054 - val_accuracy: 0.9961 - val_loss: 0.0325
Epoch 129/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0055 - val_accuracy: 0.9956 - val_loss: 0.0300
Epoch 130/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0066 - val_accuracy: 0.9962 - val_loss: 0.0291
Epoch 131/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0056 - val_accuracy: 0.9961 - val_loss: 0.0313
Epoch 132/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0069 - val_accuracy: 0.9965 - val_loss: 0.0275
Epoch 133/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0061 - val_accuracy: 0.9963 - val_loss: 0.0249
Epoch 134/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0062 - val_accuracy: 0.9966 - val_loss: 0.0234
Epoch 135/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0051 - val_accuracy: 0.9967 - val_loss: 0.0247
Epoch 136/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0047 - val_accuracy: 0.9962 - val_loss: 0.0258
Epoch 137/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0060 - val_accuracy: 0.9963 - val_loss: 0.0269
Epoch 138/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0054 - val_accuracy: 0.9963 - val_loss: 0.0254
Epoch 139/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0058 - val_accuracy: 0.9958 - val_loss: 0.0256
Epoch 140/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0052 - val_accuracy: 0.9962 - val_loss: 0.0274
Epoch 141/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0062 - val_accuracy: 0.9961 - val_loss: 0.0263
Epoch 142/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0062 - val_accuracy: 0.9965 - val_loss: 0.0326
Epoch 143/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0065 - val_accuracy: 0.9957 - val_loss: 0.0303
Epoch 144/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0061 - val_accuracy: 0.9958 - val_loss: 0.0276
Epoch 145/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0054 - val_accuracy: 0.9956 - val_loss: 0.0311
Epoch 146/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0054 - val_accuracy: 0.9962 - val_loss: 0.0321
Epoch 147/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0050 - val_accuracy: 0.9961 - val_loss: 0.0293
Epoch 148/200
394/394 - 1s - 2ms/step - accuracy: 0.9982 - loss: 0.0049 - val_accuracy: 0.9956 - val_loss: 0.0322
Epoch 149/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0053 - val_accuracy: 0.9960 - val_loss: 0.0321
Epoch 150/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0051 - val_accuracy: 0.9965 - val_loss: 0.0287
Epoch 151/200
394/394 - 1s - 2ms/step - accuracy: 0.9982 - loss: 0.0051 - val_accuracy: 0.9963 - val_loss: 0.0311
Epoch 152/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0068 - val_accuracy: 0.9965 - val_loss: 0.0272
Epoch 153/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0051 - val_accuracy: 0.9964 - val_loss: 0.0297
Epoch 154/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0054 - val_accuracy: 0.9956 - val_loss: 0.0315
Epoch 155/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0057 - val_accuracy: 0.9962 - val_loss: 0.0274
Epoch 156/200
394/394 - 1s - 2ms/step - accuracy: 0.9982 - loss: 0.0050 - val_accuracy: 0.9967 - val_loss: 0.0261
Epoch 157/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0050 - val_accuracy: 0.9969 - val_loss: 0.0269
Epoch 158/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0048 - val_accuracy: 0.9962 - val_loss: 0.0271
Epoch 159/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0075 - val_accuracy: 0.9962 - val_loss: 0.0274
Epoch 160/200
394/394 - 1s - 2ms/step - accuracy: 0.9976 - loss: 0.0077 - val_accuracy: 0.9963 - val_loss: 0.0309
Epoch 161/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0058 - val_accuracy: 0.9967 - val_loss: 0.0296
Epoch 162/200
394/394 - 1s - 2ms/step - accuracy: 0.9982 - loss: 0.0045 - val_accuracy: 0.9963 - val_loss: 0.0317
Epoch 163/200
394/394 - 1s - 2ms/step - accuracy: 0.9982 - loss: 0.0046 - val_accuracy: 0.9966 - val_loss: 0.0300
Epoch 164/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0053 - val_accuracy: 0.9965 - val_loss: 0.0292
Epoch 165/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0047 - val_accuracy: 0.9962 - val_loss: 0.0315
Epoch 166/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0049 - val_accuracy: 0.9969 - val_loss: 0.0290
Epoch 167/200
394/394 - 1s - 2ms/step - accuracy: 0.9982 - loss: 0.0047 - val_accuracy: 0.9961 - val_loss: 0.0318
Epoch 168/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0057 - val_accuracy: 0.9961 - val_loss: 0.0299
Epoch 169/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0061 - val_accuracy: 0.9968 - val_loss: 0.0287
Epoch 170/200
394/394 - 1s - 2ms/step - accuracy: 0.9979 - loss: 0.0059 - val_accuracy: 0.9961 - val_loss: 0.0288
Epoch 171/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0051 - val_accuracy: 0.9971 - val_loss: 0.0289
Epoch 172/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0054 - val_accuracy: 0.9969 - val_loss: 0.0277
Epoch 173/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0049 - val_accuracy: 0.9967 - val_loss: 0.0272
Epoch 174/200
394/394 - 1s - 2ms/step - accuracy: 0.9980 - loss: 0.0057 - val_accuracy: 0.9959 - val_loss: 0.0333
Epoch 175/200
394/394 - 1s - 2ms/step - accuracy: 0.9978 - loss: 0.0069 - val_accuracy: 0.9966 - val_loss: 0.0262
Epoch 176/200
394/394 - 1s - 2ms/step - accuracy: 0.9981 - loss: 0.0052 - val_accuracy: 0.9965 - val_loss: 0.0253
Epoch 177/200

In [ ]:
test_results = classifier.evaluate(
    X_test,
    y_test_encoded,
    batch_size=BATCH_SIZE,
    verbose=0,
    return_dict=True,
)

In [ ]:
for metric_name, metric_value in test_results.items():
    print(
        f"{metric_name:12s}: "
        f"{metric_value:.6f}"
    )

accuracy    : 0.768497
loss        : 13.181582

In [ ]:
predicted_probabilities = classifier.predict(
    X_test,
    batch_size=BATCH_SIZE,
    verbose=0,
)

y_pred = np.argmax(
    predicted_probabilities,
    axis=1,
)

In [ ]:
accuracy = accuracy_score(
    y_test,
    y_pred,
)

weighted_recall = recall_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0,
)

weighted_precision = precision_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0,
)


confusion = confusion_matrix(
    y_test,
    y_pred,
    labels=np.arange(NUMBER_OF_CLASSES),
)

class_support = confusion.sum(axis=1)
total_samples = class_support.sum()

per_class_fpr = []

for class_index in range(NUMBER_OF_CLASSES):
    tp = confusion[class_index, class_index]
    fn = confusion[class_index, :].sum() - tp
    fp = confusion[:, class_index].sum() - tp
    tn = total_samples - tp - fn - fp

    fpr = (
        fp / (fp + tn)
        if (fp + tn) > 0
        else 0.0
    )

    per_class_fpr.append(fpr)

per_class_fpr = np.asarray(per_class_fpr)

weighted_fpr = np.average(
    per_class_fpr,
    weights=class_support,
)

weighted_f1 = f1_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0,
)



print(f"Accuracy:           {accuracy:.6f}")
print(f"Weighted precision: {weighted_precision:.6f}")
print(f"Weighted recall:    {weighted_recall:.6f}")
print(f"False positive rate:{weighted_fpr:.6f}")
print(f"Weighted F1-score:  {weighted_f1:.6f}")
print("Confusion matrix")
print("----------------")
print(confusion)

Accuracy:           0.768497
Weighted precision: 0.785796
Weighted recall:    0.768497
False positive rate:0.151213
Weighted F1-score:  0.735697
Confusion matrix
----------------
[[8971  506  228    4    2]
 [1046 6311   66   35    0]
 [ 272  434 1684   23    8]
 [2327    3   85  336    3]
 [ 171    0    4    2   23]]

In [ ]:
classifier.save("/content/drive/MyDrive/Models_Table_5/DNN_Kunang.keras")
autoencoder.save("/content/drive/MyDrive/Models_Table_5/DAE_Kunang.keras")

# **Hyperparameter Optimization for 1D-CNN-Based Network Intrusion Detection Using GA and PSO [29]**

In [93]:
df = pd.concat([X_train_df, X_test_df])
df.describe(include="all")

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
count,142218.000000,142218.0,142218.0,142218.0,1.422180e+05,1.422180e+05,142218.000000,142218.000000,142218.000000,142218.000000,...,142218.000000,142218.000000,142218.000000,142218.000000,142218.000000,142218.000000,142218.000000,142218.000000,142218.000000,142218.000000
unique,NaN,6.0,133.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,1.0,24.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,97540.0,38323.0,71205.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,277.798999,NaN,NaN,NaN,4.155920e+04,1.760007e+04,0.000218,0.020440,0.000211,0.187592,...,183.933440,119.613649,0.535200,0.084050,0.146106,0.030506,0.254900,0.250106,0.136882,0.137063
std,2462.514477,NaN,NaN,NaN,5.527968e+06,3.784560e+06,0.014762,0.239676,0.019842,1.997390,...,98.532002,111.258170,0.448051,0.194163,0.308942,0.108665,0.427749,0.428956,0.323371,0.335920
min,0.000000,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,87.000000,11.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,NaN,NaN,NaN,4.400000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,255.000000,72.000000,0.600000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,NaN,NaN,NaN,2.780000e+02,5.727500e+02,0.000000,0.000000,0.000000,0.000000,...,255.000000,255.000000,1.000000,0.070000,0.050000,0.010000,0.540000,0.470000,0.000000,0.000000
max,57715.000000,NaN,NaN,NaN,1.379964e+09,1.309937e+09,1.000000,3.000000,3.000000,101.000000,...,255.000000,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [92]:
df['label'] = df['label'].map(lambda a: 0 if a == 'normal' else 1)
df.info()

KeyError: 'label'

In [ ]:
df.drop('num_outbound_cmds', axis=1, inplace=True)

In [ ]:
df.isnull().sum().sort_values(ascending = False)

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
label                          0
dtype: int64

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.describe(include="all")

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
count,147888.000000,147888,147888,147888,1.478880e+05,1.478880e+05,147888.000000,147888.000000,147888.000000,147888.000000,...,147888.000000,147888.000000,147888.000000,147888.000000,147888.000000,147888.000000,147888.000000,147888.000000,147888.000000,147888.000000
unique,NaN,3,70,11,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,tcp,http,SF,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,121351,48168,89385,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,277.956508,NaN,NaN,NaN,4.039199e+04,1.716056e+04,0.000196,0.020434,0.000203,0.189982,...,119.403522,0.533860,0.084158,0.144168,0.030009,0.256827,0.251995,0.135880,0.136047,0.479559
std,2465.844177,NaN,NaN,NaN,5.421103e+06,3.711392e+06,0.014002,0.240056,0.019458,2.017317,...,111.204097,0.447948,0.193983,0.306437,0.106313,0.428872,0.430101,0.322299,0.334874,0.499584
min,0.000000,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,11.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,NaN,NaN,NaN,4.400000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,72.000000,0.590000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,NaN,NaN,NaN,2.780000e+02,5.810000e+02,0.000000,0.000000,0.000000,0.000000,...,255.000000,1.000000,0.070000,0.050000,0.010000,0.632500,0.550000,0.000000,0.000000,1.000000
max,57715.000000,NaN,NaN,NaN,1.379964e+09,1.309937e+09,1.000000,3.000000,3.000000,101.000000,...,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
le_protocol_type = LabelEncoder()
le_service = LabelEncoder()
le_flag = LabelEncoder()

In [ ]:
df['protocol_type_encoded'] = le_protocol_type.fit_transform(df.protocol_type)
df['service_encoded'] = le_service.fit_transform(df.service)
df['flag_encoded'] = le_flag.fit_transform(df.flag)

/tmp/ipykernel_1808/4148780589.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['protocol_type_encoded'] = le_protocol_type.fit_transform(df.protocol_type)
/tmp/ipykernel_1808/4148780589.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['service_encoded'] = le_service.fit_transform(df.service)
/tmp/ipykernel_1808/4148780589.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['flag_encoded'] = le_flag.fit_transform(df.flag)

In [ ]:
protocol_type_ = OneHotEncoder()
service_ = OneHotEncoder()
flag_ = OneHotEncoder()


X = protocol_type_.fit_transform(df.protocol_type_encoded.values.reshape(-1,1)).toarray()
Xm = service_.fit_transform(df.service_encoded.values.reshape(-1,1)).toarray()
Xmm = flag_.fit_transform(df.flag_encoded.values.reshape(-1,1)).toarray()

dfOneHot = pd.DataFrame(X, columns=["protocol_type_"+str(int(i)) for i in range(X.shape[1])])
df = pd.concat([df.reset_index(drop=True), dfOneHot], axis=1)

dfOneHot2 = pd.DataFrame(Xm, columns=["service_"+str(int(i)) for i in range(Xm.shape[1])])
df = pd.concat([df.reset_index(drop=True), dfOneHot2], axis=1)

dfOneHot3 = pd.DataFrame(Xmm, columns=["flag_"+str(int(i)) for i in range(Xmm.shape[1])])
df = pd.concat([df.reset_index(drop=True), dfOneHot3], axis=1)

In [ ]:
df.drop(columns=['protocol_type','service','flag'], inplace = True )
df.shape

(147888, 125)

In [ ]:
bestfeatuers=SelectKBest(score_func=chi2,k=100)
inp=df.iloc[:,0:125]
fit=bestfeatuers.fit(inp,df['label'])
dfscores=pd.DataFrame(fit.scores_)
dfcol=pd.DataFrame(inp.columns)
featurescore=pd.concat([dfcol,dfscores],axis=1)
featurescore.columns=['feature','score']
k=featurescore['feature']
t=featurescore.nlargest(100,'score')
li=list(t['feature'])
print("Top 100 features:")
#print("\n")
for x in li:
    print(x,end=", ")

X=df[li].drop(columns=['label'])
y=df[li]['label']

Top 100 features:
src_bytes, dst_bytes, duration, dst_host_srv_count, count, dst_host_count, service_encoded, label, flag_encoded, logged_in, dst_host_srv_serror_rate, flag_5, srv_serror_rate, serror_rate, dst_host_serror_rate, num_root, service_24, flag_9, num_compromised, dst_host_same_srv_rate, service_49, same_srv_rate, rerror_rate, srv_rerror_rate, dst_host_srv_rerror_rate, dst_host_rerror_rate, srv_count, service_12, flag_1, protocol_type_2, service_54, protocol_type_0, dst_host_diff_srv_rate, diff_srv_rate, service_14, service_15, wrong_fragment, flag_4, protocol_type_encoded, flag_2, srv_diff_host_rate, service_60, service_28, num_file_creations, service_2, service_66, service_20, service_6, service_5, service_29, service_67, service_69, service_41, service_68, service_47, service_8, service_7, service_58, service_26, service_10, service_21, service_9, service_57, service_16, dst_host_same_src_port_rate, service_33, service_59, service_65, service_17, service_36, service_11, service_23, service_13, service_35, service_34, service_30, service_37, service_32, service_63, num_access_files, service_40, service_38, service_39, flag_10, service_31, service_56, service_42, service_18, num_failed_logins, flag_6, service_4, service_55, hot, service_0, service_43, service_19, flag_8, dst_host_srv_diff_host_rate, su_attempted, flag_3,

In [ ]:
# Split the data into train (80%) and test (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Split the training data further into train (80%) and validation (20%) sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.125, random_state=42)

In [ ]:
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

input_shape = (X_train.shape[1], 1)
output_classes = 1

In [ ]:
model = Sequential()

model.add(Conv1D(filters=32, kernel_size=9, activation='relu', input_shape=(input_shape)))
model.add(MaxPooling1D(pool_size=5))

model.add(Conv1D(filters=64, kernel_size=9, activation='relu'))
model.add(MaxPooling1D(pool_size=5))

model.add(Dropout(0.253378))
model.add(Flatten())

for _ in range(1):
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.253378))

model.add(Dense(output_classes, activation='sigmoid'))

optimizer = Adam(learning_rate=0.000471)
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 91, 32)         │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 18, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 10, 64)         │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 2, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 2, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 35,457 (138.50 KB)

 Trainable params: 35,457 (138.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(X_train, y_train, batch_size=32, epochs=72, validation_data=(X_val, y_val))

Epoch 1/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 20s 4ms/step - accuracy: 0.9516 - loss: 0.1259 - val_accuracy: 0.9720 - val_loss: 0.0712
Epoch 2/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9727 - loss: 0.0730 - val_accuracy: 0.9784 - val_loss: 0.0557
Epoch 3/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9780 - loss: 0.0590 - val_accuracy: 0.9808 - val_loss: 0.0466
Epoch 4/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9803 - loss: 0.0532 - val_accuracy: 0.9822 - val_loss: 0.0441
Epoch 5/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9815 - loss: 0.0494 - val_accuracy: 0.9830 - val_loss: 0.0428
Epoch 6/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9825 - loss: 0.0467 - val_accuracy: 0.9830 - val_loss: 0.0444
Epoch 7/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9833 - loss: 0.0444 - val_accuracy: 0.9855 - val_loss: 0.0374
Epoch 8/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9840 - loss: 0.0430 - val_accuracy: 0.9850 - val_loss: 0.0382
Epoch 9/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9843 - loss: 0.0420 - val_accuracy: 0.9875 - val_loss: 0.0345
Epoch 10/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9844 - loss: 0.0409 - val_accuracy: 0.9851 - val_loss: 0.0351
Epoch 11/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9853 - loss: 0.0393 - val_accuracy: 0.9871 - val_loss: 0.0365
Epoch 12/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9859 - loss: 0.0380 - val_accuracy: 0.9877 - val_loss: 0.0331
Epoch 13/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9857 - loss: 0.0386 - val_accuracy: 0.9871 - val_loss: 0.0320
Epoch 14/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9857 - loss: 0.0375 - val_accuracy: 0.9873 - val_loss: 0.0330
Epoch 15/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9866 - loss: 0.0362 - val_accuracy: 0.9865 - val_loss: 0.0340
Epoch 16/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9867 - loss: 0.0359 - val_accuracy: 0.9874 - val_loss: 0.0340
Epoch 17/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9869 - loss: 0.0352 - val_accuracy: 0.9869 - val_loss: 0.0314
Epoch 18/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9867 - loss: 0.0352 - val_accuracy: 0.9872 - val_loss: 0.0323
Epoch 19/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9872 - loss: 0.0340 - val_accuracy: 0.9869 - val_loss: 0.0326
Epoch 20/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9876 - loss: 0.0342 - val_accuracy: 0.9880 - val_loss: 0.0299
Epoch 21/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9874 - loss: 0.0338 - val_accuracy: 0.9888 - val_loss: 0.0304
Epoch 22/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9873 - loss: 0.0335 - val_accuracy: 0.9876 - val_loss: 0.0303
Epoch 23/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9875 - loss: 0.0341 - val_accuracy: 0.9886 - val_loss: 0.0307
Epoch 24/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9882 - loss: 0.0323 - val_accuracy: 0.9886 - val_loss: 0.0294
Epoch 25/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9878 - loss: 0.0322 - val_accuracy: 0.9876 - val_loss: 0.0306
Epoch 26/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9880 - loss: 0.0330 - val_accuracy: 0.9898 - val_loss: 0.0279
Epoch 27/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9884 - loss: 0.0318 - val_accuracy: 0.9895 - val_loss: 0.0284
Epoch 28/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9883 - loss: 0.0312 - val_accuracy: 0.9888 - val_loss: 0.0287
Epoch 29/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9882 - loss: 0.0316 - val_accuracy: 0.9883 - val_loss: 0.0303
Epoch 30/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9880 - loss: 0.0310 - val_accuracy: 0.9887 - val_loss: 0.0295
Epoch 31/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9882 - loss: 0.0317 - val_accuracy: 0.9893 - val_loss: 0.0282
Epoch 32/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9884 - loss: 0.0312 - val_accuracy: 0.9886 - val_loss: 0.0288
Epoch 33/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9882 - loss: 0.0305 - val_accuracy: 0.9895 - val_loss: 0.0278
Epoch 34/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9887 - loss: 0.0300 - val_accuracy: 0.9886 - val_loss: 0.0276
Epoch 35/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9884 - loss: 0.0308 - val_accuracy: 0.9878 - val_loss: 0.0305
Epoch 36/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9882 - loss: 0.0306 - val_accuracy: 0.9882 - val_loss: 0.0281
Epoch 37/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9889 - loss: 0.0299 - val_accuracy: 0.9903 - val_loss: 0.0282
Epoch 38/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9888 - loss: 0.0297 - val_accuracy: 0.9891 - val_loss: 0.0284
Epoch 39/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9888 - loss: 0.0298 - val_accuracy: 0.9886 - val_loss: 0.0278
Epoch 40/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9890 - loss: 0.0293 - val_accuracy: 0.9891 - val_loss: 0.0266
Epoch 41/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9889 - loss: 0.0292 - val_accuracy: 0.9886 - val_loss: 0.0291
Epoch 42/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9891 - loss: 0.0293 - val_accuracy: 0.9888 - val_loss: 0.0260
Epoch 43/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9891 - loss: 0.0291 - val_accuracy: 0.9904 - val_loss: 0.0274
Epoch 44/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9892 - loss: 0.0283 - val_accuracy: 0.9888 - val_loss: 0.0264
Epoch 45/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9891 - loss: 0.0280 - val_accuracy: 0.9888 - val_loss: 0.0272
Epoch 46/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9891 - loss: 0.0292 - val_accuracy: 0.9905 - val_loss: 0.0258
Epoch 47/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9896 - loss: 0.0279 - val_accuracy: 0.9904 - val_loss: 0.0264
Epoch 48/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9897 - loss: 0.0275 - val_accuracy: 0.9892 - val_loss: 0.0282
Epoch 49/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9895 - loss: 0.0278 - val_accuracy: 0.9899 - val_loss: 0.0262
Epoch 50/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9898 - loss: 0.0277 - val_accuracy: 0.9904 - val_loss: 0.0278
Epoch 51/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9897 - loss: 0.0280 - val_accuracy: 0.9901 - val_loss: 0.0258
Epoch 52/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9896 - loss: 0.0283 - val_accuracy: 0.9890 - val_loss: 0.0295
Epoch 53/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9898 - loss: 0.0276 - val_accuracy: 0.9906 - val_loss: 0.0255
Epoch 54/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9899 - loss: 0.0278 - val_accuracy: 0.9895 - val_loss: 0.0270
Epoch 55/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9897 - loss: 0.0270 - val_accuracy: 0.9895 - val_loss: 0.0257
Epoch 56/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9897 - loss: 0.0280 - val_accuracy: 0.9888 - val_loss: 0.0273
Epoch 57/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9901 - loss: 0.0267 - val_accuracy: 0.9894 - val_loss: 0.0258
Epoch 58/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9901 - loss: 0.0266 - val_accuracy: 0.9906 - val_loss: 0.0248
Epoch 59/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9897 - loss: 0.0270 - val_accuracy: 0.9907 - val_loss: 0.0250
Epoch 60/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9898 - loss: 0.0268 - val_accuracy: 0.9904 - val_loss: 0.0272
Epoch 61/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9897 - loss: 0.0263 - val_accuracy: 0.9909 - val_loss: 0.0267
Epoch 62/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9901 - loss: 0.0266 - val_accuracy: 0.9905 - val_loss: 0.0262
Epoch 63/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9899 - loss: 0.0270 - val_accuracy: 0.9899 - val_loss: 0.0271
Epoch 64/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9901 - loss: 0.0259 - val_accuracy: 0.9892 - val_loss: 0.0263
Epoch 65/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9902 - loss: 0.0270 - val_accuracy: 0.9890 - val_loss: 0.0264
Epoch 66/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9903 - loss: 0.0259 - val_accuracy: 0.9891 - val_loss: 0.0271
Epoch 67/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9904 - loss: 0.0259 - val_accuracy: 0.9905 - val_loss: 0.0250
Epoch 68/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9903 - loss: 0.0262 - val_accuracy: 0.9892 - val_loss: 0.0257
Epoch 69/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9899 - loss: 0.0283 - val_accuracy: 0.9905 - val_loss: 0.0249
Epoch 70/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9902 - loss: 0.0252 - val_accuracy: 0.9900 - val_loss: 0.0241
Epoch 71/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9905 - loss: 0.0257 - val_accuracy: 0.9888 - val_loss: 0.0255
Epoch 72/72
3236/3236 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9901 - loss: 0.0255 - val_accuracy: 0.9909 - val_loss: 0.0258

In [ ]:
y_pred = model.predict(np.expand_dims(X_test, axis=2))
y_pred = (y_pred > 0.5)


cm = confusion_matrix(y_test, y_pred)

tn, fp, fn, tp = cm.ravel()

accuracy = accuracy_score(y_test, y_pred)

recall = recall_score(
    y_test,
    y_pred,
    pos_label=1,
    zero_division=0,
)

precision = precision_score(
    y_test,
    y_pred,
    pos_label=1,
    zero_division=0,
)



false_positive_rate = (
    fp / (fp + tn)
    if (fp + tn) > 0
    else 0.0
)

f1 = f1_score(
    y_test,
    y_pred,
    pos_label=1,
    zero_division=0,
)


print("Confusion matrix")
print("----------------")
print(cm)

print("\nAttack-class metrics")
print("--------------------")
print(f"Accuracy : {accuracy:.4f} "
      f"({accuracy * 100:.2f}%)")
print(f"Detection rate : {recall:.4f} "
      f"({recall * 100:.2f}%)")
print(f"Precision      : {precision:.4f} "
      f"({precision * 100:.2f}%)")
print(f"FPR            : {false_positive_rate:.4f} "
      f"({false_positive_rate * 100:.2f}%)")
print(f"F1 score       : {f1:.4f} "
      f"({f1 * 100:.2f}%)")

925/925 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step
Confusion matrix
----------------
[[15145   127]
 [  138 14168]]

Attack-class metrics
--------------------
Accuracy : 0.9910 (99.10%)
Detection rate : 0.9904 (99.04%)
Precision      : 0.9911 (99.11%)
FPR            : 0.0083 (0.83%)
F1 score       : 0.9907 (99.07%)

In [ ]:
model.save("/content/drive/MyDrive/Models_Table_5/1DCNN_Kilichev.keras")

# **Towards Detection of Network Anomalies using Machine Learning Algorithms on the NSL-KDD Benchmark Datasets [68]**

In [97]:
RANDOM_STATE = 100

X_train_df, X_validation_df, y_train, y_validation = (
    train_test_split(
        X_train_all_df,
        y_train_all,
        test_size=0.30,
        random_state=RANDOM_STATE,
        shuffle=True,
    )
)

In [98]:
categorical_columns = [
    "protocol_type",
    "service",
    "flag",
]

numerical_columns = [
    column
    for column in X_train_df.columns
    if column not in categorical_columns
]

In [99]:
one_hot_encoder = OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=False,
        dtype=np.float32,
    )

min_max_scaler = MinMaxScaler(
    feature_range=(0.0, 1.0),
    clip=True,
)


preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            min_max_scaler,
            numerical_columns,
        ),
        (
            "categorical",
            one_hot_encoder,
            categorical_columns,
        ),
    ],
    remainder="drop",
    sparse_threshold=0.0,
)

In [100]:
X_train_processed = preprocessor.fit_transform(
    X_train_df
).astype(np.float32)

X_validation_processed = preprocessor.transform(
    X_validation_df
).astype(np.float32)

X_test_processed = preprocessor.transform(
    X_test_df
).astype(np.float32)

In [101]:
random_forest = RandomForestClassifier(
    n_estimators=300,
    random_state=100,
    n_jobs=-1,
)

random_forest.fit(
    X_train_processed,
    y_train,
)

RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=100)

In [102]:

encoded_feature_names = (
    preprocessor.get_feature_names_out()
)

feature_importances = (
    random_forest.feature_importances_
)

importance_threshold = 0.037

selected_feature_mask = (
    feature_importances >= importance_threshold
)

selected_feature_indices = np.where(
    selected_feature_mask
)[0]

selected_feature_names = encoded_feature_names[
    selected_feature_mask
]

print("Importance threshold:", importance_threshold)
print(
    "Number of selected features:",
    len(selected_feature_names),
)

Importance threshold: 0.037
Number of selected features: 9

In [103]:
feature_importance_df = pd.DataFrame(
    {
        "feature": encoded_feature_names,
        "importance": feature_importances,
        "selected": selected_feature_mask,
    }
)

feature_importance_df = (
    feature_importance_df
    .sort_values(
        by="importance",
        ascending=False,
    )
    .reset_index(drop=True)
)

print(feature_importance_df.head(20))

                                   feature  importance  selected
0                     numerical__src_bytes    0.132624      True
1                     numerical__dst_bytes    0.101803      True
2                     categorical__flag_SF    0.063152      True
3            numerical__dst_host_srv_count    0.050663      True
4        numerical__dst_host_same_srv_rate    0.049871      True
5                 numerical__diff_srv_rate    0.049460      True
6                 numerical__same_srv_rate    0.044356      True
7        numerical__dst_host_diff_srv_rate    0.041900      True
8                         numerical__count    0.040663      True
9                     numerical__logged_in    0.033835     False
10     numerical__dst_host_srv_serror_rate    0.028551     False
11  numerical__dst_host_same_src_port_rate    0.025404     False
12         numerical__dst_host_rerror_rate    0.023471     False
13               numerical__dst_host_count    0.022565     False
14         numerical__dst_host_serror_rate    0.022391     False
15         categorical__protocol_type_icmp    0.019792     False
16               categorical__service_http    0.019680     False
17              numerical__srv_serror_rate    0.019568     False
18  numerical__dst_host_srv_diff_host_rate    0.018645     False
19                  numerical__serror_rate    0.014027     False

In [104]:
X_train_selected = X_train_processed[
    :,
    selected_feature_mask,
]

X_validation_selected = X_validation_processed[
    :,
    selected_feature_mask,
]

X_test_selected = X_test_processed[
    :,
    selected_feature_mask,
]

print("Selected training shape:  ", X_train_selected.shape)
print("Selected validation shape:", X_validation_selected.shape)
print("Selected testing shape:   ", X_test_selected.shape)

Selected training shape:   (103961, 9)
Selected validation shape: (44556, 9)
Selected testing shape:    (22544, 9)

In [105]:
knn_classifier = KNeighborsClassifier(
    n_neighbors=5,
    weights="uniform",
    algorithm="auto",
    leaf_size=30,
    metric="euclidean",
    n_jobs=-1,
)

In [106]:
knn_classifier.fit(
    X_train_selected,
    y_train,
)

KNeighborsClassifier(metric='euclidean', n_jobs=-1)

In [107]:
_ = knn_classifier.predict_proba(
    X_validation_selected[:100]
)

In [108]:
test_probabilities = (
    knn_classifier.predict_proba(
        X_test_selected
    )
)

test_anomaly_probabilities = (
    test_probabilities[:, 1]
)

test_predictions = (
    test_anomaly_probabilities >= 0.5
).astype(np.int32)


test_confusion = confusion_matrix(
    y_test,
    test_predictions,
    labels=[0, 1],
)

accuracy = accuracy_score(
    y_test,
    test_predictions,
)

precision = precision_score(
    y_test,
    test_predictions,
    pos_label=1,
    zero_division=0,
)

recall = recall_score(
    y_test,
    test_predictions,
    pos_label=1,
    zero_division=0,
)

test_tn = test_confusion[0, 0]
test_fp = test_confusion[0, 1]
test_fn = test_confusion[1, 0]
test_tp = test_confusion[1, 1]

false_positive_rate = test_fp / (
    test_fp + test_tn
)

f1 = f1_score(
    y_test,
    test_predictions,
    pos_label=1,
    zero_division=0,
)

In [109]:
print("Confusion matrix")
print("----------------")
print(test_confusion)

print("\nAttack-class metrics")
print("--------------------")
print(f"Accuracy : {accuracy:.4f} "
      f"({accuracy * 100:.2f}%)")
print(f"Detection rate : {recall:.4f} "
      f"({recall * 100:.2f}%)")
print(f"Precision      : {precision:.4f} "
      f"({precision * 100:.2f}%)")
print(f"FPR            : {false_positive_rate:.4f} "
      f"({false_positive_rate * 100:.2f}%)")
print(f"F1 score       : {f1:.4f} "
      f"({f1 * 100:.2f}%)")

Confusion matrix
----------------
[[ 9213   498]
 [ 1397 11436]]

Attack-class metrics
--------------------
Accuracy : 0.9159 (91.59%)
Detection rate : 0.8911 (89.11%)
Precision      : 0.9583 (95.83%)
FPR            : 0.0513 (5.13%)
F1 score       : 0.9235 (92.35%)

In [ ]:
import joblib

saved_bundle = {
    "preprocessor": preprocessor,
    "random_forest": random_forest,
    "selected_feature_mask": selected_feature_mask,
    "encoded_feature_names": encoded_feature_names,
    "selected_feature_names": selected_feature_names,
    "knn_classifier": knn_classifier,
    "categorical_columns": categorical_columns,
    "numerical_columns": numerical_columns,
    "original_feature_columns": list(
        X_train_all_df.columns
    ),
    "class_names": ["Normal", "Anomaly"],
}

joblib.dump(
    saved_bundle,
    "/content/drive/MyDrive/Models_Table_7/KNN_Vibhute.joblib",
)

['/content/drive/MyDrive/Models_Table_7/KNN_Vibhute.joblib']

# **Ckan: Convolutional kolmogorov–arnold networks model for intrusion detection in iot environment [3]**

In [110]:
import random
import time
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.compose import ColumnTransformer
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

from torch.utils.data import DataLoader, TensorDataset

In [121]:
SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", DEVICE)


BATCH_SIZE = 32
LEARNING_RATE = 0.001
EPOCHS = 20
VALIDATION_SIZE = 0.10

NUMBER_OF_CLASSES = 2

CLASS_NAMES = [
    "Normal",
    "Attack",
]

Device: cuda

In [113]:
train_df = pd.read_csv(
    "/content/drive/MyDrive/Colab Notebooks/DATASETS/NSLKDD/NSL_KDD_Train.csv",
    names=column_names,
    header=None,
)

test_df = pd.read_csv(
    "/content/drive/MyDrive/Colab Notebooks/DATASETS/NSLKDD/NSL_KDD_Test.csv",
    names=column_names,
    header=None,
)

print("Training data shape:", train_df.shape)
print("Testing data shape:", test_df.shape)

print(train_df.head())

Training data shape: (125973, 43)
Testing data shape: (22544, 43)
   duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0         0           tcp  ftp_data   SF        491          0     0
1         0           udp     other   SF        146          0     0
2         0           tcp   private   S0          0          0     0
3         0           tcp      http   SF        232       8153     0
4         0           tcp      http   SF        199        420     0

   wrong_fragment  urgent  hot  ...  dst_host_same_srv_rate  \
0               0       0    0  ...                    0.17
1               0       0    0  ...                    0.00
2               0       0    0  ...                    0.10
3               0       0    0  ...                    1.00
4               0       0    0  ...                    1.00

   dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                    0.03                         0.17
1                    0.60                         0.88
2                    0.05                         0.00
3                    0.00                         0.03
4                    0.00                         0.00

   dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                         0.00                  0.00
1                         0.00                  0.00
2                         0.00                  1.00
3                         0.04                  0.03
4                         0.00                  0.00

   dst_host_srv_serror_rate  dst_host_rerror_rate  dst_host_srv_rerror_rate  \
0                      0.00                  0.05                      0.00
1                      0.00                  0.00                      0.00
2                      1.00                  0.00                      0.00
3                      0.01                  0.00                      0.01
4                      0.00                  0.00                      0.00

     label  difficulty
0   normal         NaN
1   normal         NaN
2  neptune         NaN
3   normal         NaN
4   normal         NaN

[5 rows x 43 columns]

In [114]:
train_labels = (
    all_df["label"]
    .astype(str)
    .str.strip()
    .str.rstrip(".")
    .str.lower()
)

test_labels = (
    test_df["label"]
    .astype(str)
    .str.strip()
    .str.rstrip(".")
    .str.lower()
)




y_train_all = (
    train_labels != "normal"
).astype(np.int64).to_numpy()

y_test = (
    test_labels != "normal"
).astype(np.int64).to_numpy()


print("Training label values:", np.unique(y_train_all))
print("Testing label values:", np.unique(y_test))

Training label values: [0 1]
Testing label values: [0 1]

In [115]:
X_train_all_df = all_df.drop(
    columns=[
        "label",
        "difficulty",
    ]
).copy()

X_test_df = test_df.drop(
    columns=[
        "label",
        "difficulty",
    ]
).copy()


print("Raw training feature shape:", X_train_all_df.shape)
print("Raw testing feature shape:", X_test_df.shape)

Raw training feature shape: (148517, 41)
Raw testing feature shape: (22544, 41)

In [122]:
(
    X_train_df,
    X_validation_df,
    y_train,
    y_validation,
) = train_test_split(
    X_train_all_df,
    y_train_all,
    test_size=VALIDATION_SIZE,
    random_state=SEED,
    stratify=y_train_all,
    shuffle=True,
)


print("Internal training shape:", X_train_df.shape)
print("Validation shape:       ", X_validation_df.shape)
print("Official test shape:    ", X_test_df.shape)

Internal training shape: (133665, 41)
Validation shape:        (14852, 41)
Official test shape:     (22544, 41)

In [123]:
categorical_columns = [
    "protocol_type",
    "service",
    "flag",
]

numerical_columns = [
    column
    for column in X_train_df.columns
    if column not in categorical_columns
]


print("Categorical columns:", categorical_columns)
print("Number of numerical columns:", len(numerical_columns))

Categorical columns: ['protocol_type', 'service', 'flag']
Number of numerical columns: 38

In [124]:
one_hot_encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False,
    dtype=np.float32,
)


min_max_scaler = MinMaxScaler(
    feature_range=(0.0, 1.0),
    clip=True,
)

preprocessor = ColumnTransformer(
transformers=[
    (
        "numerical",
        min_max_scaler,
        numerical_columns,
    ),
    (
        "categorical",
        one_hot_encoder,
        categorical_columns,
    ),
],
remainder="drop",
sparse_threshold=0.0,
)

In [125]:
X_train_processed = preprocessor.fit_transform(
    X_train_df
).astype(np.float32)

X_validation_processed = preprocessor.transform(
    X_validation_df
).astype(np.float32)

X_test_processed = preprocessor.transform(
    X_test_df
).astype(np.float32)

In [126]:
print("Processed training shape:  ", X_train_processed.shape)
print("Processed validation shape:", X_validation_processed.shape)
print("Processed testing shape:   ", X_test_processed.shape)

Processed training shape:   (133665, 122)
Processed validation shape: (14852, 122)
Processed testing shape:    (22544, 122)

In [127]:
X_train_tensor = torch.from_numpy(
    X_train_processed
).unsqueeze(1)

X_validation_tensor = torch.from_numpy(
    X_validation_processed
).unsqueeze(1)

X_test_tensor = torch.from_numpy(
    X_test_processed
).unsqueeze(1)


y_train_tensor = torch.from_numpy(
    y_train
).long()

y_validation_tensor = torch.from_numpy(
    y_validation
).long()

y_test_tensor = torch.from_numpy(
    y_test
).long()


print("Training tensor shape:", X_train_tensor.shape)
print("Validation tensor shape:", X_validation_tensor.shape)
print("Testing tensor shape:", X_test_tensor.shape)

Training tensor shape: torch.Size([133665, 1, 122])
Validation tensor shape: torch.Size([14852, 1, 122])
Testing tensor shape: torch.Size([22544, 1, 122])

In [128]:
train_dataset = TensorDataset(
    X_train_tensor,
    y_train_tensor,
)

validation_dataset = TensorDataset(
    X_validation_tensor,
    y_validation_tensor,
)

test_dataset = TensorDataset(
    X_test_tensor,
    y_test_tensor,
)


pin_memory = DEVICE.type == "cuda"


train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0,
    pin_memory=pin_memory,
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=pin_memory,
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=pin_memory,
)

In [129]:
class KANLinear(nn.Module):

    def __init__(
        self,
        in_features,
        out_features,
        grid_size=5,
        spline_order=3,
        grid_range=(-1.0, 1.0),
    ):
        super().__init__()

        self.in_features = in_features
        self.out_features = out_features
        self.grid_size = grid_size
        self.spline_order = spline_order

        self.number_of_spline_coefficients = (
            grid_size + spline_order
        )

        grid_step = (
            grid_range[1] - grid_range[0]
        ) / grid_size

        grid = (
            torch.arange(
                -spline_order,
                grid_size + spline_order + 1,
                dtype=torch.float32,
            )
            * grid_step
            + grid_range[0]
        )

        grid = grid.expand(
            in_features,
            -1,
        ).contiguous()

        self.register_buffer(
            "grid",
            grid,
        )

        # One base weight per connection
        self.base_weight = nn.Parameter(
            torch.empty(
                out_features,
                in_features,
            )
        )

        # grid_size + spline_order = 8 coefficients
        self.spline_weight = nn.Parameter(
            torch.empty(
                out_features,
                in_features,
                self.number_of_spline_coefficients,
            )
        )

        # One spline scale per connection
        self.spline_scaler = nn.Parameter(
            torch.empty(
                out_features,
                in_features,
            )
        )

        nn.init.kaiming_uniform_(
            self.base_weight,
            a=np.sqrt(5),
        )

        nn.init.normal_(
            self.spline_weight,
            mean=0.0,
            std=0.02,
        )

        nn.init.ones_(
            self.spline_scaler
        )


    def b_splines(self, x):

        # x shape:
        # (batch_size, in_features)

        x_expanded = x.unsqueeze(-1)

        grid = self.grid

        bases = (
            (
                x_expanded >= grid[:, :-1]
            )
            &
            (
                x_expanded < grid[:, 1:]
            )
        ).to(x.dtype)

        for order in range(
            1,
            self.spline_order + 1,
        ):
            left_numerator = (
                x_expanded
                - grid[:, :-(order + 1)]
            )

            left_denominator = (
                grid[:, order:-1]
                - grid[:, :-(order + 1)]
            )

            right_numerator = (
                grid[:, order + 1:]
                - x_expanded
            )

            right_denominator = (
                grid[:, order + 1:]
                - grid[:, 1:-order]
            )

            left_term = (
                left_numerator
                / left_denominator
                * bases[:, :, :-1]
            )

            right_term = (
                right_numerator
                / right_denominator
                * bases[:, :, 1:]
            )

            bases = left_term + right_term

        return bases.contiguous()


    def forward(self, x):

        # Base branch
        base_output = F.linear(
            F.silu(x),
            self.base_weight,
        )

        # B-spline branch
        spline_bases = self.b_splines(x)

        scaled_spline_weights = (
            self.spline_weight
            * self.spline_scaler.unsqueeze(-1)
        )

        spline_output = F.linear(
            spline_bases.reshape(
                x.shape[0],
                -1,
            ),
            scaled_spline_weights.reshape(
                self.out_features,
                -1,
            ),
        )

        return base_output + spline_output

In [130]:
class CKANBinary(nn.Module):

    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv1d(
            in_channels=1,
            out_channels=32,
            kernel_size=3,
            stride=1,
            padding=0,
            bias=True,
        )

        self.conv2 = nn.Conv1d(
            in_channels=32,
            out_channels=64,
            kernel_size=3,
            stride=1,
            padding=0,
            bias=True,
        )

        self.adaptive_pool = (
            nn.AdaptiveAvgPool1d(
                output_size=1
            )
        )

        self.kan = KANLinear(
            in_features=64,
            out_features=2,
            grid_size=5,
            spline_order=3,
            grid_range=(-1.0, 1.0),
        )


    def forward(self, x):

        x = self.conv1(x)
        x = F.relu(x)

        x = self.conv2(x)
        x = F.relu(x)

        x = self.adaptive_pool(x)

        # (batch, 64, 1) -> (batch, 64)
        x = x.squeeze(-1)

        logits = self.kan(x)

        return logits

In [131]:
model = CKANBinary().to(DEVICE)

print(model)

total_trainable_parameters = sum(
    parameter.numel()
    for parameter in model.parameters()
    if parameter.requires_grad
)

print(
    "Total trainable parameters:",
    total_trainable_parameters,
)

CKANBinary(
  (conv1): Conv1d(1, 32, kernel_size=(3,), stride=(1,))
  (conv2): Conv1d(32, 64, kernel_size=(3,), stride=(1,))
  (adaptive_pool): AdaptiveAvgPool1d(output_size=1)
  (kan): KANLinear()
)
Total trainable parameters: 7616

In [132]:
criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=0.01,
)

In [133]:
training_loss_history = []
validation_loss_history = []

training_accuracy_history = []
validation_accuracy_history = []


if DEVICE.type == "cuda":
    torch.cuda.synchronize()

training_start_time = time.perf_counter()


for epoch in range(EPOCHS):


    model.train()

    training_loss_sum = 0.0
    training_correct = 0
    training_samples = 0


    for batch_features, batch_labels in train_loader:

        batch_features = batch_features.to(
            DEVICE,
            non_blocking=True,
        )

        batch_labels = batch_labels.to(
            DEVICE,
            non_blocking=True,
        )


        optimizer.zero_grad(
            set_to_none=True
        )


        logits = model(
            batch_features
        )

        loss = criterion(
            logits,
            batch_labels,
        )


        loss.backward()

        optimizer.step()


        batch_size = batch_features.size(0)

        training_loss_sum += (
            loss.item() * batch_size
        )

        training_predictions = torch.argmax(
            logits,
            dim=1,
        )

        training_correct += (
            training_predictions
            == batch_labels
        ).sum().item()

        training_samples += batch_size


    epoch_training_loss = (
        training_loss_sum
        / training_samples
    )

    epoch_training_accuracy = (
        training_correct
        / training_samples
    )


    model.eval()

    validation_loss_sum = 0.0
    validation_correct = 0
    validation_samples = 0


    with torch.no_grad():

        for (
            batch_features,
            batch_labels,
        ) in validation_loader:

            batch_features = batch_features.to(
                DEVICE,
                non_blocking=True,
            )

            batch_labels = batch_labels.to(
                DEVICE,
                non_blocking=True,
            )


            logits = model(
                batch_features
            )

            loss = criterion(
                logits,
                batch_labels,
            )


            batch_size = batch_features.size(0)

            validation_loss_sum += (
                loss.item() * batch_size
            )

            validation_predictions = torch.argmax(
                logits,
                dim=1,
            )

            validation_correct += (
                validation_predictions
                == batch_labels
            ).sum().item()

            validation_samples += batch_size


    epoch_validation_loss = (
        validation_loss_sum
        / validation_samples
    )

    epoch_validation_accuracy = (
        validation_correct
        / validation_samples
    )


    training_loss_history.append(
        epoch_training_loss
    )

    validation_loss_history.append(
        epoch_validation_loss
    )

    training_accuracy_history.append(
        epoch_training_accuracy
    )

    validation_accuracy_history.append(
        epoch_validation_accuracy
    )


    print(
        f"Epoch {epoch + 1:02d}/{EPOCHS} | "
        f"train loss: {epoch_training_loss:.6f} | "
        f"train acc: {epoch_training_accuracy:.4f} | "
        f"val loss: {epoch_validation_loss:.6f} | "
        f"val acc: {epoch_validation_accuracy:.4f}"
    )


if DEVICE.type == "cuda":
    torch.cuda.synchronize()

training_time = (
    time.perf_counter()
    - training_start_time
)


print(
    f"\nTotal training time: "
    f"{training_time:.3f} seconds"
)

Epoch 01/20 | train loss: 0.356947 | train acc: 0.8610 | val loss: 0.290460 | val acc: 0.8903
Epoch 02/20 | train loss: 0.247209 | train acc: 0.8982 | val loss: 0.223625 | val acc: 0.9053
Epoch 03/20 | train loss: 0.215121 | train acc: 0.9100 | val loss: 0.199446 | val acc: 0.9115
Epoch 04/20 | train loss: 0.196087 | train acc: 0.9200 | val loss: 0.186112 | val acc: 0.9278
Epoch 05/20 | train loss: 0.184606 | train acc: 0.9267 | val loss: 0.173269 | val acc: 0.9342
Epoch 06/20 | train loss: 0.176511 | train acc: 0.9316 | val loss: 0.169532 | val acc: 0.9334
Epoch 07/20 | train loss: 0.167702 | train acc: 0.9365 | val loss: 0.159841 | val acc: 0.9416
Epoch 08/20 | train loss: 0.162698 | train acc: 0.9385 | val loss: 0.151799 | val acc: 0.9445
Epoch 09/20 | train loss: 0.158181 | train acc: 0.9404 | val loss: 0.153503 | val acc: 0.9413
Epoch 10/20 | train loss: 0.153799 | train acc: 0.9423 | val loss: 0.149163 | val acc: 0.9406
Epoch 11/20 | train loss: 0.150604 | train acc: 0.9438 | val loss: 0.141234 | val acc: 0.9481
Epoch 12/20 | train loss: 0.148345 | train acc: 0.9445 | val loss: 0.155700 | val acc: 0.9371
Epoch 13/20 | train loss: 0.145790 | train acc: 0.9451 | val loss: 0.146335 | val acc: 0.9393
Epoch 14/20 | train loss: 0.144264 | train acc: 0.9454 | val loss: 0.142904 | val acc: 0.9443
Epoch 15/20 | train loss: 0.143062 | train acc: 0.9458 | val loss: 0.132607 | val acc: 0.9510
Epoch 16/20 | train loss: 0.142057 | train acc: 0.9461 | val loss: 0.130084 | val acc: 0.9528
Epoch 17/20 | train loss: 0.139443 | train acc: 0.9470 | val loss: 0.128332 | val acc: 0.9510
Epoch 18/20 | train loss: 0.139308 | train acc: 0.9468 | val loss: 0.137860 | val acc: 0.9451
Epoch 19/20 | train loss: 0.136777 | train acc: 0.9483 | val loss: 0.144783 | val acc: 0.9426
Epoch 20/20 | train loss: 0.135668 | train acc: 0.9480 | val loss: 0.127691 | val acc: 0.9521

Total training time: 345.919 seconds

In [134]:
model.eval()

test_loss_sum = 0.0
test_sample_count = 0

all_test_labels = []
all_test_predictions = []
all_test_attack_probabilities = []


with torch.no_grad():

    for (
        batch_features,
        batch_labels,
    ) in test_loader:

        batch_features = batch_features.to(
            DEVICE,
            non_blocking=True,
        )

        batch_labels = batch_labels.to(
            DEVICE,
            non_blocking=True,
        )


        logits = model(
            batch_features
        )

        loss = criterion(
            logits,
            batch_labels,
        )


        probabilities = torch.softmax(
            logits,
            dim=1,
        )

        predictions = torch.argmax(
            logits,
            dim=1,
        )


        batch_size = batch_features.size(0)

        test_loss_sum += (
            loss.item() * batch_size
        )

        test_sample_count += batch_size


        all_test_labels.append(
            batch_labels.cpu().numpy()
        )

        all_test_predictions.append(
            predictions.cpu().numpy()
        )

        all_test_attack_probabilities.append(
            probabilities[:, 1]
            .cpu()
            .numpy()
        )


y_test_true = np.concatenate(
    all_test_labels
)

y_test_pred = np.concatenate(
    all_test_predictions
)

y_test_attack_probability = np.concatenate(
    all_test_attack_probabilities
)


test_loss = (
    test_loss_sum
    / test_sample_count
)

In [135]:

accuracy = accuracy_score(
    y_test_true,
    y_test_pred,
)

precision = precision_score(
    y_test_true,
    y_test_pred,
    pos_label=1,
    zero_division=0,
)

recall = recall_score(
    y_test_true,
    y_test_pred,
    pos_label=1,
    zero_division=0,
)

f1 = f1_score(
    y_test_true,
    y_test_pred,
    pos_label=1,
    zero_division=0,
)

cm = confusion_matrix(
    y_test_true,
    y_test_pred,
    labels=[0, 1],
)


true_negative = cm[0, 0]
false_positive = cm[0, 1]
false_negative = cm[1, 0]
true_positive = cm[1, 1]

fpr = (false_positive/ (false_positive+ true_negative))

In [136]:
print("Confusion matrix")
print("----------------")
print(confusion_matrix)

print("\nAttack-class metrics")
print("--------------------")
print(f"Accuracy : {accuracy:.4f} "
      f"({accuracy * 100:.2f}%)")
print(f"Detection rate : {recall:.4f} "
      f"({recall * 100:.2f}%)")
print(f"Precision      : {precision:.4f} "
      f"({precision * 100:.2f}%)")
print(f"FPR            : {fpr:.4f} "
      f"({fpr * 100:.2f}%)")
print(f"F1 score       : {f1:.4f} "
      f"({f1 * 100:.2f}%)")

Confusion matrix
----------------
<function confusion_matrix at 0x7e0f21137a60>

Attack-class metrics
--------------------
Accuracy : 0.8865 (88.65%)
Detection rate : 0.8298 (82.98%)
Precision      : 0.9661 (96.61%)
FPR            : 0.0385 (3.85%)
F1 score       : 0.8928 (89.28%)